### ISSUE TITLE
Can not access any wiki page

### ISSUE THREAD

**Issue by mecp** [ohmybash/oh-my-bash#10]
I am not able access any of the wiki pages. 

For example if I navigate to this url https://github.com/ohmybash/oh-my-bash/wiki/Themes
Github shows this message: `You do not have permission to update this wiki.`

And all links on the wiki page anyway show up in `red` suggesting linked pages do not exist.

**Comment by nntoan** [comment]
@mecp Sorry, I don't know what settings make that permission denied. But I've just changed a config `Restrict editing to users in teams with push access only` to `false`.

Can you please check and let me know if it works?

**Comment by mecp** [comment]
@nntoan I do not get permission error now. But it seems all the pages linked on wiki Home page are empty, when I click on for example "Themes", github takes me to "Create a new Page" page. Do those pages exist?

**Comment by nntoan** [comment]
@mecp The red link means that page does not exist yet. So sorry that I don't have enough time to create all of the documentation. Feel free to contribute then :(

**Comment by codypiersall** [comment]
The README says that screenshots of themes are available on the Wiki.. and has a broken link to https://github.com/ohmybash/oh-my-bash/wiki/Themes... has that page ever existed?

I'm trying to understand whether something tragic happened to the Wiki, or whether someone just needs to create that page.

**Comment by nityanandagohain** [comment]
I am facing the same issue.

**Comment by nntoan** [comment]
Closed as duplicate to #1
