### ISSUE TITLE
how can i fix or change this?

### ISSUE THREAD

**Issue by azamet90** [ohmybash/oh-my-bash#122]
![image](https://user-images.githubusercontent.com/44042178/72201397-7d469700-348e-11ea-97c6-4c8083870e51.png)
as you can see if i do cd command it is showing extra line which is /home/azamet/Belgeler/
i dont want it shows on second line how to change it?

**Comment by safeith** [comment]
I think you can disable it by adding the following line to your `.bashrc`
`alias cd='>/dev/null cd'`

**Comment by nntoan** [comment]
What is the theme you are using @azamet90 ? There might be some extra aliases per theme.

**Comment by azamet90** [comment]
> I think you can disable it by adding the following line to your `.bashrc`
> `alias cd='>/dev/null cd'`

oh thx it works

**Comment by azamet90** [comment]
> I think you can disable it by adding the following line to your `.bashrc`
> `alias cd='>/dev/null cd'`

![image](https://user-images.githubusercontent.com/44042178/84592497-ddcb6d00-ae4e-11ea-815a-e42bccc71853.png)
my last question sir: how to disable the exit result on same way?
