### ISSUE TITLE
i did installed go but...

### ISSUE THREAD

**Issue by azamet90** [ohmybash/oh-my-bash#123]
i did installed go with this tutorial which was working everytime:
https://docs.google.com/document/d/1Wm7eFA97HaXaoo98pI7t61rxmJXfKmrrJ7nIjRuo6BE/edit

but i have $PATH problems which is because of this tool i believe because of path is not there so i cannot run go command without doing export command which is not persistence ... pls help me about that

**Comment by nntoan** [comment]
Instead of using `nano .profile`, try manually add the export command into `.bashrc`

**Comment by azamet90** [comment]
thx it works
