### ISSUE TITLE
ls coloring not working

### ISSUE THREAD

**Issue by mjgritli** [ohmybash/oh-my-bash#128]
Dear Developer,
I loved your work of "oh-my-bash" I switched to bash again after some time with zsh due to the capabilities you added to bash, very nice work. However:
ls commands no longer have color support, I tried adding the coloring aliases from my old .bashrc file but it isn't working neither.
please help fix this issue

**Comment by nkoutsov** [comment]
You could add an alias to the file `~/.oh-my-bash/aliases/general.aliases.sh` 
like this: 
`alias ls='ls --color=auto'`
