### ISSUE TITLE
Unable to disable 'ls' aliases

### ISSUE THREAD

**Issue by owenlejeune** [ohmybash/oh-my-bash#134]
I have a custom alias file called `shell.aliases.sh` located in `~/.oh-my-bash/custom/aliases` which contains various aliases, including some for ls (such as `la`) which have different behavior than those found in ls.aliases.sh.  My list of aliases in `.bashrc` only contains my `shell` alias file, but I still get the behavior of the built-in `ls` aliases, and my custom aliases are not printed in the output of `alias`, while the oh-my-bash ones are.  Any ideas why this could be happening?

**Comment by nntoan** [comment]
@owenlejeune Did you add `shell` into your `.bashrc` alias section?

**Comment by owenlejeune** [comment]
@nntoan yes, `shell` is the only thing I have listed in my alias section

**Comment by owenlejeune** [comment]
My bad, turns out I had my file misnamed `shell.ailases.sh`.  Renaming it fixed the issue
