### ISSUE TITLE
set CASE_SENSITIVE="true" in .bashrc does not give case-sensitive completion

### ISSUE THREAD

**Issue by scstsfxt** [ohmybash/oh-my-bash#137]
The environment is standard /bin/bash of CentOS6, and the issue is as stated in title.

**Comment by grisu48** [comment]
I noticed the same behaviour and would also like to have case-sensitive completion.

**Comment by tuxmontero** [comment]
same issue here, you shouldn't activate that function by default

**Comment by kamichal** [comment]
Same in Arch:
```Linux xxx 5.4.36-1-MANJARO #1 SMP PREEMPT Wed Apr 29 18:47:01 UTC 2020 x86_64 GNU/Linux
```

**Comment by saul365** [comment]
I attempted to solve it already tested it in Debian and Manjaro  it just changes 2 files in PR #180

**Comment by Cherkah** [comment]
hi there,
what about the sensitive_case fix. cause on manjaro, konsole and yakuake do not reacts when the setting =true

**Comment by akinomyoga** [comment]
This should have been solved by PR #180, which was merged on Feb 16, 2023. Closing.
