### ISSUE TITLE
Install oh-my-bash in a script

### ISSUE THREAD

**Issue by rafaelribeiroo** [ohmybash/oh-my-bash#141]
Hello,

I use this script to install oh-my-bash

```
#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install git curl -y
chsh -s $(which zsh)
bash -c "$(curl --fail --silent --location 'https://raw.github.com/ohmybash/oh-my-bash/master/tools/install.sh')"
########################
mkdir ~/bin

stuff...
```

After install the oh-my-bash, the script will exit and the reamining commands are not executed. What should I do if I want to execute it?

Thanks

**Comment by rafaelribeiroo** [comment]
It's easy to develop a unattended install like oh-my-zsh?
Stuff here: https://github.com/ohmyzsh/ohmyzsh#unattended-install

**Comment by akinomyoga** [comment]
Now the option `--unattended` is supported in #276.
