### ISSUE TITLE
Agnoster theme not working as expected

### ISSUE THREAD

**Issue by tbhaxor** [ohmybash/oh-my-bash#144]
OS: Manjaro Arch Linux
Bash Version: 5.0.16(1)-release

![image](https://user-images.githubusercontent.com/28386721/78769685-4dcefa00-79ab-11ea-925c-cd3d2157a38e.png)

**Comment by mariusz-suchodolski** [comment]
Refer to [powerline/fonts](https://github.com/powerline/fonts) repo - you're missing them.

**Comment by tbhaxor** [comment]
@mariusz-suchodolski already installed from aur

**Comment by planetceres** [comment]
@tbhaxor - I had the same problem, but resolved following this sequence:

1. Open Terminal
2. Go to  `Edit` > `Preferences`
3. Check `Custom Font`
4. Select a Powerline font (i.e. `Meslo LG L`)

**Comment by Fnk95** [comment]
> @tbhaxor - I had the same problem, but resolved following this sequence:
> 
> 1. Open Terminal
> 2. Go to  `Edit` > `Preferences`
> 3. Check `Custom Font`
> 4. Select a Powerline font (i.e. `Meslo LG L`)

It works for me, thank you!
