### ISSUE TITLE
I can't change theme

### ISSUE THREAD

**Issue by ghost** [ohmybash/oh-my-bash#146]
There is no OSH_THEME="powerline" variable in .bashrc and after adding this variable and changing its value to any other than default powerline nothing happens

**Comment by Israel-Laguan** [comment]
Hello, just to check, have you properly installed oh-my-bash? If yes, let's try something else:

- test if OSH installation path is correct in `.bashrc`
- try to source `$OSH/oh-my-bash.sh`
- Change any alias inside `OSH/aliases/`, open a new terminal, and test it. If it's not working you should reinstall.

Please share your findings and comments!

**Comment by WarrenWongCodes** [comment]
The variable is there however, after I change the OSH_THEME to some other theme, it will not update. Even after restarting terminal. Anyone have this issue ?

**Comment by Munsio** [comment]
I had the same problem when I updated oh-my-bash today.
Solved the issue with the following code inside my `.bashrc`

```bash
unset PROMPT_COMMAND
source "$OSH"/oh-my-bash.sh
```

I am on Suse and it seems there is a sticky `PROMPT_COMMAND` which overrules `PS1` by unsetting it the themes seems to work again.

**Comment by smarianimore** [comment]
Same problem here: whichever theme I try to set, I get a `oh-my-bash (module_require): module 'theme:powerline-icon' not found.` (example theme)

1. installation path is correct
2. sourcing doesn't work
3. aliases do not work (hence a related issue?)

FYI I'm on Ubuntu 22.04 on WSL2

**Comment by akinomyoga** [comment]
The theme `powerline-icon` is recently added and did not exist in older versions. Have you updated Oh My Bash? If not, could you try updating Oh My Bash following the description in README?

**Comment by smarianimore** [comment]
> The theme `powerline-icon` is recently added and did not exist in older versions. Have you updated Oh My Bash? If not, could you try updating Oh My Bash following the description in README?

Many thanks, I updated OMB and it worked!

However, now I see box characters, that I understand are due to missing "powerline" fonts. 
I installed them using `sudo apt-get install fonts-powerline` but I don't have ways to select them from the terminal settings as suggested, as I'm using Ubuntu on Windows 11 WSL2, and I think that settings there only show windows-installed fonts (I may be wrong)

Any idea how to fix this?

**Comment by smarianimore** [comment]
> > The theme `powerline-icon` is recently added and did not exist in older versions. Have you updated Oh My Bash? If not, could you try updating Oh My Bash following the description in README?
> 
> Many thanks, I updated OMB and it worked!
> 
> However, now I see box characters, that I understand are due to missing "powerline" fonts. I installed them using `sudo apt-get install fonts-powerline` but I don't have ways to select them from the terminal settings as suggested, as I'm using Ubuntu on Windows 11 WSL2, and I think that settings there only show windows-installed fonts (I may be wrong)
> 
> Any idea how to fix this?

Nevermind, dumb me: as Windows is rendering fonts I need to install powerline fonts in windows. 
Followed this and fixed: https://slmeng.medium.com/how-to-install-powerline-fonts-in-windows-b2eedecace58 

:FACEPALM:
