### ISSUE TITLE
Theme Upgrade

### ISSUE THREAD

**Issue by machinexa2** [ohmybash/oh-my-bash#155]
The theme powerline and agnoster are very good however there is very little vertical margin/padding (betn commands). Also wiki doesnt have guide on how to  create themes or modify them. If i could add some padding it would be good.

**Comment by pentalive** [comment]
I would like to replicate my MSDOS prompt. It uses the "Save cursor location" and "Restore cursor location" ansii sequences to keep a status line on the top row of the terminal - then only a ">:" at the point where one enters the command  (yes and or "presses the button")  If there is documentation on the available parts of a theme it would help.
