### ISSUE TITLE
[NEW PLUGIN REQUEST] autocompletion and syntax highlighting

### ISSUE THREAD

**Issue by AkhilJalagam** [ohmybash/oh-my-bash#157]
Fish-like auto-suggestions and syntax highlighting. Here are links to these plugins:

Zsh-autosuggestions (https://github.com/zsh-users/zsh-autosuggestions)
Zsh-syntax-highlighting (https://github.com/zsh-users/zsh-syntax-highlighting)

**Comment by 1900011604** [comment]
so how to install them on oh-my-bash?

**Comment by AkhilJalagam** [comment]
> so how to install them on oh-my-bash?

first, someone should write code for bash. then we can install.

**Comment by akinomyoga** [comment]
There is already an Issue suggesting autocompletions at #108.

> > so how to install them on oh-my-bash?
>
> first, someone should write code for bash. then we can install.

I have an implementation [`akinomyoga/ble.sh`](https://github.com/akinomyoga/ble.sh) that supports both autocompletions and syntax highlighting, but I'm not sure if this should be included in `oh-my-bash`. `ble.sh` is not a simple setting but implements the entire line editor by Bash scripts. The code base of `ble.sh` (about 50K LoC in total) is much larger than `oh-my-bash` and also actively changed, so I feel it is improper to include the code of `ble.sh` in `oh-my-bash`. You can separately install both `oh-my-bash` and `ble.sh` (or maybe one can add some install scripts in `oh-my-bash` as a plugin?).

**Comment by 2catycm** [comment]
> There is already an Issue suggesting autocompletions at #108.
> 
> > > so how to install them on oh-my-bash?
> > 
> > 
> > first, someone should write code for bash. then we can install.
> 
> I have an implementation [`akinomyoga/ble.sh`](https://github.com/akinomyoga/ble.sh) that supports both autocompletions and syntax highlighting, but I'm not sure if this should be included in `oh-my-bash`. `ble.sh` is not a simple setting but implements the entire line editor by Bash scripts. The code base of `ble.sh` (about 50K LoC in total) is much larger than `oh-my-bash` and also actively changed, so I feel it is improper to include the code of `ble.sh` in `oh-my-bash`. You can separately install both `oh-my-bash` and `ble.sh` (or maybe one can add some install scripts in `oh-my-bash` as a plugin?).

really good project， thank you very much

**Comment by Firestar-Reimu** [comment]
Yes, I am also using `ble.sh`
