### ISSUE TITLE
OhMyBash not rendering PowerLine characters

### ISSUE THREAD

**Issue by V4G4X** [ohmybash/oh-my-bash#188]
The simple basic ohmybash installation seems to work. However when I change the theme to a PowerLine(powerline or Agnoster) one.  
My shell doesn't render the new characters properly and I get boxes instead. 
I have Cascadia Code's PL version of fonts installed on the system too.

I am running ubuntu 20.04 on WSL2(Which I don't think should be making a difference as ohmyzsh worked in the past).
Any help is Appreciated.
https://imgur.com/a/Fg3XhOm

**Comment by sk313t0n** [comment]
Same, I just started using (at least wanted to) oh-my-bash, but urxvt does not like the ends of the arrows. Can I do anything to fix it?

**Comment by V4G4X** [comment]
> 
> 
> Same, I just started using (at least wanted to) oh-my-bash, but urxvt does not like the ends of the arrows. Can I do anything to fix it?

If you're on WSL **and** using Windows Terminal. This is how I got to fix it. 
The Cascadia PL font also had to be installed on the Windows side of things. Not just that.
I also had to update the fontface on Windows Terminal settings. 
Then suddenly it worked.

Closing the issue.
