### ISSUE TITLE
cd also does pwd (only in some cases?)

### ISSUE THREAD

**Issue by krdee1** [ohmybash/oh-my-bash#189]
Right now `cd` also does a `pwd` afterwards, but only when moving further down the file tree. Example is as follows.
![image](https://user-images.githubusercontent.com/47307377/100066864-6aa92800-2dea-11eb-9b22-d5354f0dbedf.png)
Personally I find this rather annoying, and I would love to turn it off, but after poring over the oh-my-bash files I cannot locate where this functionality is introduced. Can someone point me in the right direction?

**Comment by pradhanvickey** [comment]
any fix to this ?

**Comment by locobastos** [comment]
Does this solve your issue ?
https://github.com/ohmybash/oh-my-bash/issues/201

**Comment by krdee1** [comment]
@pradhanvickey I can confirm @locobastos has a working fix. Thank you!
