### ISSUE TITLE
which: no binary in (path)

### ISSUE THREAD

**Issue by lasers** [ohmybash/oh-my-bash#2]
After adding `oh-my-bash`, I get this with new terminals.
```
which: no aws_completer in (/usr/local/bin:/usr/bin:/bin:/snap/bin)
which: no register-python-argcomplete in (/usr/local/bin:/usr/bin:/bin:/snap/bin)
which: no jungle in (/usr/local/bin:/usr/bin:/bin:/snap/bin)
which: no kontena in (/usr/local/bin:/usr/bin:/bin:/snap/bin)
10:01:42 lasers ~ → 
```
It looks like some `oh-my-bash` completions will need to add and/or fix `/dev/null`.

**Comment by teon** [comment]
I don't understand why those binaries are necessary? I'm not using those, why should they be required?

**Comment by lasers** [comment]
I don't remember anymore. It might have been a random theme and I think I filed this because the missing binaries are drawing text on the screen instead of silently failing and keep going with fewer features/chars. Otherwise, the users could have to muck around with prompt and/or installing binaries if they want to use that theme for a while... and the next one.... and probably one more after that one too.

The themes should work with what users have and not the other way.

**Comment by Amolith** [comment]
I fixed this issue on my local installation. I found the offending lines in `~/.oh-my-bash/oh-my-bash.sh` and simply commented them out. I've pasted them below

```for completion_file in $OSH/completion/*.sh; do
  custom_completion_file="${OSH_CUSTOM}/completion/${completion_file:t}"
  [ -f "${custom_completion_file}" ] && completion_file=${custom_completion_file}
  source $completion_file
done```

**Comment by tron-solo** [comment]
You can remove the offending .sh files from`~/.oh-my-bash/completion`, this should clean things up for you.

**Comment by che666** [comment]
I have made a pull request fixing the noise.

**Comment by lasers** [comment]
I see the pull request has been merged months ago. Closing this now! Super late thanks!
