### ISSUE TITLE
How to disable full path print after cd into a directory?

### ISSUE THREAD

**Issue by gokomer** [ohmybash/oh-my-bash#201]
I couldn't find a setting for disabling the full path print after cd into a directory. Any pointers?

**Comment by locobastos** [comment]
Comment the line CDPATH="." in ~/.oh-my-bash/lib/shopt.sh

**Comment by MusKaya** [comment]
can we have this as a setting that can be toggled off in the `.bashrc` file?

**Comment by thetredev** [comment]
@MusKaya after `source "$OSH"/oh-my-bash.sh` add `unset CDPATH`

**Comment by thisisamirv** [comment]
Oh, this was driving me crazy! Thanks for the fix. It makes more sense to have it not print path dir as the default behavior.
