### ISSUE TITLE
Git Bash: Terminal starts with error after changing theme

### ISSUE THREAD

**Issue by gitwikc** [ohmybash/oh-my-bash#211]
I changed the theme to `cupcake` and restarted the terminal.
It always starts with an error:
```
bash: command substitution: line 1: syntax error near unexpected token `)'
bash: command substitution: line 1: `[[ -n $(git branch 2> /dev/null) ]] && echo " on 🌿
")'
```

The previous theme was `purity` and I didn't have such problems wit it. It is just when I changed the theme that this problem started.

**Comment by johnsonjo4531** [comment]
Same here from me, this is happening to me in git-bash on windows.

**Comment by solrevdev** [comment]
Similar here:

I get the following whenever I `source .bashrc` :

```bash
bash: /home/solrevdev/.oh-my-bash/lib/base.sh: line 209: syntax error near unexpected token `('
bash: /home/solrevdev/.oh-my-bash/lib/base.sh: line 209: `    myip () {'
```

Where line 207-212 of bash.sh is

```bash
#   myip:  displays your ip address, as seen by the Internet
#   -------------------------------------------------------------------
    myip () {
      res=$(curl -s checkip.dyndns.org | grep -Eo '[0-9\.]+')
      echo -e "Your public IP is: ${echo_bold_green} $res ${echo_normal}"
    }

```

System info:

```text
neofetch --off
solrevdev@hplaptop 
------------------ 
OS: Ubuntu 20.04.4 LTS x86_64 
Host: HP 250 G6 Notebook PC 
Kernel: 5.4.0-124-generic 
Uptime: 7 hours, 5 mins 
Packages: 3751 (dpkg), 1 (pkg), 30 (flatpak), 35 (snap) 
Shell: bash 5.0.17 
Resolution: 1920x1080 
DE: GNOME 
WM: Mutter 
WM Theme: Adwaita 
Theme: Yaru [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: terminator 
CPU: Intel i5-7200U (4) @ 3.100GHz 
GPU: Intel HD Graphics 620 
Memory: 8221MiB / 15926MiB 

```

**Comment by akinomyoga** [comment]
@solrevdev The message is the same, but I think the actual problem is different from the original one. In your case, I think the shell function `myip` defined in oh-my-bash is conflicting with an alias `myip` defined outside of oh-my-bash. Do you define a custom alias `myip`?

**Comment by solrevdev** [comment]
> @solrevdev The message is the same, but I think the actual problem is different from the original one. In your case, I think the shell function `myip` defined in oh-my-bash is conflicting with an alias `myip` defined outside of oh-my-bash. Do you define a custom alias `myip`?

That’s it! Thanks! That was exactly the issue there was another function named that which I could comment out and bingo!
