### ISSUE TITLE
How to remove time from the terminal prompt

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [ohmybash/oh-my-bash#219]
![image](https://user-images.githubusercontent.com/11331989/121540008-bf795c80-ca23-11eb-9ecc-65996e64c9ec.png)

I want to get rid of this time from my terminal but not sure how to go about it. Any one can point me to something?

**Comment by HopefulFire** [comment]
what theme is that?

**Comment by joyetgeorge** [comment]
According to the theme edit the THEME_SHOW_CLOCK line to false (THEME_SHOW_CLOCK=false) in the themes directory (.oh-my-bash/themes/#your_theme/#your_theme.sh)

You can check your theme in the .bashrc file (OSH_THEME="#your_theme")

**Comment by nntoan** [comment]
@ankitsinghaniyaz Comment of @joyetgeorge is correct, set `THEME_SHOW_CLOCK=false` should turn off the clock. I recommend you copy the theme you want to turn off into `custom/themes`, then adjust the variable over there.

In the future, we will allow to adjust the variable from `.bashrc` which provided the more convenient than now.

**Comment by xgdgsc** [comment]
Might consider making no time the default?
