### ISSUE TITLE
Oh-my-bash not working for root user.

### ISSUE THREAD

**Issue by SisyphusIsntHappy** [ohmybash/oh-my-bash#222]
Platform : Void Linux.

I installed `oh-my-bash` via wget, it installs without any errors, and seems to be working on the shell from which it was installed. But newly opened root shells does not seem to respect the new `.bashrc` .

**Comment by HopefulFire** [comment]
The root directory for root shells is not the same as your user's. The root user has a special `/root/` directory. To install oh-my-bash with your favorite presets:
`sudo su`
`cd`
`bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)`
`cp /home/your_user_name/.bashrc .bashrc`

**Comment by xcodz-dot** [comment]
Here you go

```bash
sudo -s
bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)
cp ~
. .bashrc
```

The above will let you use oh my bash in root shell. Now restart your terminal by closing and reopening. All should work now.
