### ISSUE TITLE
SDKMAN! plugin init messes up NVM installation

### ISSUE THREAD

**Issue by agreeff** [ohmybash/oh-my-bash#224]
greetings.. interestingly, I only discovered this issue when switching my Pop!_OS shell from `bash` to `zsh`.

basically, the current initialisation logic in [`sdkman.plugin.sh`](https://github.com/ohmybash/oh-my-bash/blob/4db7436384e0ddfa62911a101b69dd03a0df53fe/plugins/sdkman/sdkman.plugin.sh) causes NVM to be installed to `$HOME/.sdkman` instead of `$HOME/.nvm`.

after manually fixing this file locally and moving my installed Node versions and aliases to the correct place, everything worked as expected in both Bash and ZSH.

**Comment by agreeff** [comment]
closing this issue as I'm ditching this @agreeff account and moving things over to my personal @ZaLiTHkA account.

I do feel like this still needs some attention though.. so I'll dig into it in a fresh virtual environment when I get a chance, and (if I find a reproducible problem) I'll log a new issue with the appropriate account. 👍🏼

**Comment by akinomyoga** [comment]
This has been fixed in #218 and in #225.
