### ISSUE TITLE
Suggest removing the a option from the alias l

### ISSUE THREAD

**Issue by fz420** [ohmybash/oh-my-bash#227]
The `l` command alias has the `-a` option turned on by default, can you set the default value to this: `l='ls -lthF'`

Most of the time, I don't want to see hidden files (because there are quite a lot of them); unless I want to explicitly see hidden files, I would do something like this
`ls -a`
or 
`la`

like this:
![ls-cmd.png](https://i.loli.net/2021/07/07/uTwA6jsJVr4bMKq.png)

**Comment by nntoan** [comment]
@fz420 you can override this as a custom aliases (remember to use the full path, just in case you already use alias for ls)

**Comment by fz420** [comment]
> @fz420 you can override this as a custom aliases (remember to use the full path, just in case you already use alias for ls)

I have already done so.

I sent this suggestion considering that most people don't need to see hidden files every time and only use the -a option when they explicitly need it.

Based on the fact that "most people don't need to see hidden files every time", I think oh-my-bash should default this setting to "out-of-the-box"
