### ISSUE TITLE
"gpu" alias definition in git plugin gets used when not command

### ISSUE THREAD

**Issue by prehensilecode** [ohmybash/oh-my-bash#229]
When I enable the `git` plugin, doing the following
```
grep gpu *.txt
```
results in
```
grep: push: No such file or directory
grep: upstream: No such file or directory
```

This is even if more than one of the `.txt` files contains the string "`gpu`".

**Comment by prehensilecode** [comment]
I believe this is due to the alias for `grep` being defined with a whitespace at the end:
```
alias grep='grep '
```

This is defined in `.oh-my-bash/lib/grep.sh`

**Comment by nntoan** [comment]
@prehensilecode Can you open a PR for this?

**Comment by akinomyoga** [comment]
@nntoan Actually, @prehensilecode had already opened the corresponding PR at #232 (and previously #230). I'll consider the change again.
