### ISSUE TITLE
[question] `agnoster` theme: how to break prompt into 2 lines? [path display + prompt]

### ISSUE THREAD

**Issue by dennismayr** [ohmybash/oh-my-bash#231]
Hi!

I've just installed `oh-my-bash` to replace `oh-my-zsh` on a computer where setting `zsh` as default shell breaks some things.

On my GUI machine, I use `oh-my-zsh` with the `agnoster` theme, adding the following code to `~/.zshrc` to break the prompt into 2 lines, which I find more comfortable to read:

```zsh
# 'Agnoster' theme mod: new prompt line
prompt_end() {
  if [[ -n $CURRENT_BG ]]; then
      print -n "%{%k%F{$CURRENT_BG}%}$SEGMENT_SEPARATOR"
  else
      print -n "%{%k%}"
  fi
  print -n "%{%f%}"
  CURRENT_BG=''

  #Adds the new line and > as the start character.
  printf "\n >";
}
```

This changes
```zsh
dmayr@ThinkPad-T410s > ~/Documentos/DEV/Code/Rust/hello_rocket > | develop|>  # current prompt
```
to
```zsh
dmayr@ThinkPad-T410s > ~/Documentos/DEV/Code/Rust/hello_rocket > | develop|
 >  # my prompt style with the modification
```

How can I achieve the same result with `oh-my-bash`? (I'm kind of a `bash` n00b)
This would allow me to go back to `bash` without sacrificing my workflow.

**Comment by locobastos** [comment]
Define the variable PS1 with an '\n' inside. Example:

```
PS1="[\D{%F %T}]-[\u @ \h (${HOST_IP})]-[${PWD}]${normal}\n > "
```

will print:

```
[2021-08-16 12:20:45]-[my_user @ my_server_name (218.108.149.373)]-[/home/my_user]
 >
```

and you can write your command after the '$' symbol:

```
[2021-08-16 12:20:45]-[my_user @ my_server_name (218.108.149.373)]-[/home/my_user]
 > cat /etc/centos-release
CentOS Linux release 7.9.2009 (Core)
```

**Comment by dennismayr** [comment]
Thanks for the tip! I'll experiment with this over the day. Cheers!
