### ISSUE TITLE
Install in Dockerfile will make docker build hanging

### ISSUE THREAD

**Issue by district10** [ohmybash/oh-my-bash#241]
`exec bash; source $HOME/.bashrc` in [`tools/install.sh`](https://github.com/ohmybash/oh-my-bash/blob/master/tools/install.sh) will make `docker build` hanging there. Remove this line and it goes well.

It happends sometimes (not always, I didn't find a pattern). Have no idea why.

**Comment by baumannsven** [comment]
Like this:

nohup bash -ci "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)" &> /dev/null

and after:

source ~/.bashrc

**Comment by district10** [comment]
It works. 🚀

**Comment by district10** [comment]
It works. 🚀

**Comment by district10** [comment]
Still having this problem...
