### ISSUE TITLE
How to add something to PATH using oh-my-bash?

### ISSUE THREAD

**Issue by Rz-Rz** [ohmybash/oh-my-bash#243]
I tried adding the following: export PATH="~/.axiom/interact/" to my .bashrc, but I just managed to crash my terminal really bad. I've checked the ~/.oh-my-bash folder to see where a PATH might be set, but I don't see one in the shell file, or in the aliases or in the completions. It seems now that all the basic commands such as cat, grep and so on, are not on my path anymore causing my terminal to become unusable.

**Comment by Rz-Rz** [comment]
I fixed my issue by adding this line export PATH="~/.local/bin/:$PATH" at the end of my bashrc file.

**Comment by akinomyoga** [comment]
> export PATH="~/.local/bin/:$PATH"

FYI, in general, the tilde shouldn't be quoted inside the double quotations. The tilde is supposed to be expanded by the shell expansions, but the tilde will not be expanded if it is quoted. To expand the tilde, one needs to directly put the tilde outside the double quotations as

```bash
export PATH=~/.local/bin:$PATH
```

It should also be noted that the right-hand side of variable assignments in the arguments of `export` is not subject to pathname expansions and word splitting, so `$PATH` doesn't need to be enclosed in double quotations.
