### ISSUE TITLE
t: command not found issue with modern-t theme

### ISSUE THREAD

**Issue by shubhsboson** [ohmybash/oh-my-bash#249]
Hi I am facing this issue with modern-t theme , ironically it's also in the screenshot attached with the theme.

In the code line attached I see it's calling 't' command is this a thing is linux I am not aware about ?
https://github.com/ohmybash/oh-my-bash/blob/4db7436384e0ddfa62911a101b69dd03a0df53fe/themes/modern-t/modern-t.theme.sh#L44

**Comment by akinomyoga** [comment]
According to a PR in `bash-it` https://github.com/Bash-it/bash-it/pull/1742/files, Modern T theme seems to work with https://github.com/sjl/t.

**Comment by shubhsboson** [comment]
Oh! Cool🥶 , I didn't know 't' is an actual command and now that I've found it it looks like it is super awesome. Thanks a lot.

**Comment by akinomyoga** [comment]
Oh, thanks for the reply. I have now updated the `modern-t` theme so that it outputs the URL of `t` when the command is not found. Thank you!
