### ISSUE TITLE
Install/uninstall seems broken on ubuntu, WSL

### ISSUE THREAD

**Issue by FrankvdStam** [ohmybash/oh-my-bash#253]
After installing with curl, terminal shows:

```
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
: No such file or directoryash/oh-my-bash.sh
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
```

Trying to uninstall shows:

```
frank@FrankDesktop:/mnt/c/projects$ sh ~/.oh-my-bash/tools/uninstall.sh
: not found/.oh-my-bash/tools/uninstall.sh: 2:
Are you sure you want to remove Oh My Bash? [y/N] y
: bad variable namebash/tools/uninstall.sh: 3: read: confirmation
/home/frank/.oh-my-bash/tools/uninstall.sh: 38: Syntax error: end of file unexpected (expecting "then")
```

I've tried [this](https://github.com/ohmybash/oh-my-bash/issues/66) but did not fix the problem for me.

**Comment by sulo1337** [comment]
> After installing with curl, terminal shows:
> 
> ```
> : command not found
> : command not found
> : command not found
> : command not found
> : command not found
> : command not found
> : command not found
> : command not found
> : command not found
> : command not found
> : command not found
> : command not found
> : command not found
> : command not found
> : command not found
> : command not found
> : No such file or directoryash/oh-my-bash.sh
> : command not found
> : command not found
> : command not found
> : command not found
> : command not found
> : command not found
> ```
> 
> Trying to uninstall shows:
> 
> ```
> frank@FrankDesktop:/mnt/c/projects$ sh ~/.oh-my-bash/tools/uninstall.sh
> : not found/.oh-my-bash/tools/uninstall.sh: 2:
> Are you sure you want to remove Oh My Bash? [y/N] y
> : bad variable namebash/tools/uninstall.sh: 3: read: confirmation
> /home/frank/.oh-my-bash/tools/uninstall.sh: 38: Syntax error: end of file unexpected (expecting "then")
> ```
> 
> I've tried [this](https://github.com/ohmybash/oh-my-bash/issues/66) but did not fix the problem for me.

I get the same thing. It works in a docker ubuntu container but not WSL2 ubuntu distro.

**Comment by spitant** [comment]
I had the same issue, it is due to git configuration autocrtf must be disable in order to have linux endline.

`git config --global core.autocrlf false`

**Comment by FrankvdStam** [comment]
@spitant confirmed, if I set autocrlf to false, it does work.
I don't consider this a fix though, lets hope we get a proper fix 😄 

@sulo1337 see the above workaround, might help you.

**Comment by FrankvdStam** [comment]
Just found out you only need autoclrf false during installation - setting it back to true afterwards doesn't break the installation
