### ISSUE TITLE
Cannot install latest on Mac due to Bash 4.0 Error

### ISSUE THREAD

**Issue by daninthewoods** [ohmybash/oh-my-bash#27]
Quick installer errors out saying "ERROR: Sorry, you need at least bash-4.0 to run this script.", but the install instructions say oh-my-bash is best for MacOS and does not indicate Bash 4.0 is required.

MacOS default is currently GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)

**Comment by natarajmb** [comment]
Seems like an issue, I have a fresh install of MacOS High Sierra and got the same error. Followed this to upgrade to Bash 4 on Mac. http://clubmate.fi/upgrade-to-bash-4-in-mac-os-x/ assuming you have Brew installed. 

Note: If you lose the ability to get into the shell to install bash 4, move .bashrc file from the HOME directory. Use following shortcut on Finder to show hidden files in the HOME directory - CMD+SHIFT+DOT

**Comment by daninthewoods** [comment]
Thanks. I can't upgrade because the teams here use bash and all expect our own dev scripts to work on a mac.  If I upgrade I'm sure I'll inadvertently introduce a bash4 dependency during some future work.

I'm all for progress, but why force bash v4 min-requirement and make many of your users find it harder to 'just install and go'.  oh-my-zsh 'just works' sorry!

**Comment by natarajmb** [comment]
A lot of people with Mac who blindly run the installer, like we both did will have a broken system once the installer has done its job. As you have rightly pointed out there is nothing in README to indicate this runs on a 4.x version of Bash. I felt it would be better to prevent and advise rather than handing over a broken system.

Regarding forcing users to upgrade to version 4, you better be the judge - google for "bash versions on mac".

I doubt you will get all developers to test across a 3.x version of Bash every time they make a change. It's my personal opinion may be project leads here would think otherwise.

**Comment by nntoan** [comment]
I will keep this open to reverting the compatible with 3.x.x in the next refactor. At the beginning, it's compatible with 3.x.x (I originally develop it on macOS first).

**Comment by rm-rf-etc** [comment]
Running macOS Sierra, 10.12.6. Not sure if anyone noticed, but the value in $BASH_VERSION doesn't match that actual version of bash that's running.
```
rob::Robs-MacBook-Air { ~/projects }-> echo "$BASH_VERSION"
3.2.57(1)-release
rob::Robs-MacBook-Air { ~/projects }-> bash --version
GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin16.7.0)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
rob::Robs-MacBook-Air { ~/projects }-> which bash
/usr/local/bin/bash
rob::Robs-MacBook-Air { ~/projects }-> type bash
bash is hashed (/usr/local/bin/bash)
```

I can't remember how I fixed this on my iMac or why this problem occurs.

**Comment by rm-rf-etc** [comment]
I remembered. Here's the fix.

Not sure if editing `/etc/shells` is required but I started by adding `/usr/local/bin/bash` to the top of this file.

After that, open the preferences for Terminal and do this:
![terminal preferences1](https://i.imgur.com/QBJv7X3.png)
![terminal preferences1](https://i.imgur.com/ofl9H2Z.png)

**Comment by xudeheng** [comment]
> dang! I tried executing this :
> 
> ```
> bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
> ```
> and it works. the markdown on [this page](https://github.com/ohmybash/oh-my-bash) is misleading

Thansk your hinting.

$BASH_VERSION in "sh" is "sh-3.2"  , we should use correct version shell to run install.sh.

**Comment by nntoan** [comment]
Should be resolved in #39

**Comment by nntoan** [comment]
Closed as #39 merged to master.

**Comment by CodeNewman** [comment]
1. update bash https://clubmate.fi/upgrade-to-bash-4-in-mac-os-x/
2. bash -c "$(wget https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh -O -)"

**Comment by wangxin100037** [comment]
I had similar problem, no matter how many times chsh I ran, I always have bash --version 3.27 but $BASH_VERSION 5.07, finally solved this by running:

/usr/local/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

**Comment by Fanor31** [comment]
> dang! Intenté ejecutar esto:
> 
> ```
> bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
> ```
> 
> y funciona. la rebaja en [esta página](https://github.com/ohmybash/oh-my-bash) es engañosa

Eres el Puto amoooooo funcionaaaaa
