### ISSUE TITLE
Unattended install

### ISSUE THREAD

**Issue by monc949** [ohmybash/oh-my-bash#275]
Can’t seem to find any documentation on whether or not there is an unattended install option like oh-my-zsh

**Comment by akinomyoga** [comment]
Thanks for your feedback! Could you explain what is the *unattended installation*? According to the [ohmyzsh](https://github.com/ohmyzsh/ohmyzsh#unattended-install) page, is the difference from the normal installation just that it doesn't start a new Bash session after the completion? As far as I have quickly checked the installation script of `oh-my-bash`, it doesn't seem to attempt to change the default shell.

**Comment by monc949** [comment]
I am trying to run the install through a script and once oh my bash is installed, the following commands are not run as oh my bash starts a new shell

**Comment by akinomyoga** [comment]
I have implemented the option in the `support-unattended-install` branch #276 (e222d00). I would appreciate it if you could test the branch. You can test the installation script of that branch by the following commands:

```bash
url=https://raw.githubusercontent.com/ohmybash/oh-my-bash/support-unattended-install/tools/install.sh
bash -c "$(curl -fsSL "$url")" --unattended
bash -c "$(wget "$url" -O -)" --unattended
```

Thank you!

**Comment by akinomyoga** [comment]
FYI, I have found a related issue #141.

**Comment by akinomyoga** [comment]
Although it seems there is no reply, the change works as expected in my environment. I've merged the change. Thank you for the report.

**Comment by monc949** [comment]
Hi, 
Apologies for not replying, I was on a holiday/vacation for the last week.
Thank you so much.

**Comment by akinomyoga** [comment]
Thank you for the information! We are now refactoring oh-my-bash, and there are several changes in the waiting list. I just wanted to merge this into the master to avoid conflicts with other changes on the install script (such as #284).

If you find any issue related to this new option, please feel free to reopen this issue or create a new one!
