### ISSUE TITLE
Command `which' deprecated

### ISSUE THREAD

**Issue by FajarKim** [ohmybash/oh-my-bash#291]
Command 'which'  is deprecated in my terminal. Use command 'command -v' instead of command 'which'.
![Screenshot_2022_0110_163800](https://user-images.githubusercontent.com/86386385/148744788-e11be3c4-4de3-4d44-ad50-6bf3dfc05a06.png)

**Comment by akinomyoga** [comment]
Thank you for the report. This is a duplicate of #239, which is currently in progress.
