### ISSUE TITLE
Custom aliases package not found after latest upgrade

### ISSUE THREAD

**Issue by c2lhu** [ohmybash/oh-my-bash#294]
Oh-my-bash (module_require): package 'alias:myaliases' not found.

I might have missed some new development since I haven't upgraded for some months. But my custom aliases file is not found anymore.

**Comment by akinomyoga** [comment]
Thank you for the report. We have recently changed the searching logic of packages, and also there are *additional fixes* in the latest `master`. When did you last update OMB? Does it reproduce with the current latest version? If so, could you provide us with the actual filepath of your `myaliases.aliases.sh` and the values of `$OSH` and `$OSH_CUSTOM`?

**Comment by c2lhu** [comment]
Thank you for your reply. It could be the name 
The path is
/home/myhome/.oh-my-bash/custom/aliases/myaliases.sh

And the values are
/home/myhome/.oh-my-bash

And 
home/myhome/.oh-my-bash/custom

**Comment by akinomyoga** [comment]
Hmm, OK. Actually `$OSH_CUSTOM/aliases/myaliases.sh` is a very old name that has stopped working in commit 53fb803 (2019-01) three years before. I guess your aliases are actually not loaded for these three years. We have been just silently ignoring aliases that are not found, but we just recently started to output error messages when they are not found. Anyway, thank you again for reporting the issue.
