### ISSUE TITLE
agnoster theme isn't included

### ISSUE THREAD

**Issue by mpepping** [ohmybash/oh-my-bash#3]
The **agnoster** theme is mentioned in the `README.md`, but isn't included in the repository. It saner to refer to a theme that exist in the repository.

**Comment by RazZziel** [comment]
And the https://github.com/ohmybash/oh-my-bash/wiki/External-themes page isn't available either, it redirects to https://github.com/ohmybash/oh-my-bash

**Comment by googley** [comment]
Up

**Comment by nntoan** [comment]
Closed as duplicate to #1
