### ISSUE TITLE
Oh my bash does not install in bash version 5

### ISSUE THREAD

**Issue by Arwiim** [ohmybash/oh-my-bash#301]
When i try to install via sh or wget this happend
![Screenshot from 2022-02-03 14-20-56](https://user-images.githubusercontent.com/53288078/152395004-e94c00e9-4d70-4458-9470-22f4fb9d1f2e.png)

But my bash version is this (the latest 5.0.17) 
![Screenshot from 2022-02-03 14-22-21](https://user-images.githubusercontent.com/53288078/152395173-b6cb644c-37b3-4e86-a258-8a0c646ddd3f.png)

**Comment by akinomyoga** [comment]
![image](https://user-images.githubusercontent.com/8982192/152433638-c50205ec-a014-40cd-87e1-49eb6bdf727b.png)

Thank you for the report! As in the error message, you need to run the installation script with Bash but had run it using `sh`. Is the error message insufficient? Maybe later I'll update the error message. If you have any suggestions on the wording, please feel free to provide us with it.

**Comment by akinomyoga** [comment]
Now the old command on the web page has been fixed in https://github.com/ohmybash/ohmybash.github.io/pull/3. I have also update the error message in commit 5e9c2d99f01047f13c410f17643c69c6a3c8d46a.
