### ISSUE TITLE
"bash: type: append_prompt_command_override: not found" message appearing on Ubuntu 16.04 after upgrade

### ISSUE THREAD

**Issue by OptimistLabyrinth** [ohmybash/oh-my-bash#31]
today, 2018-08-14, I upgrade oh-my-bash through terminal command.
After doing that, whenever I open terminal I see 
[ bash: type: append_prompt_command_override: not found ]
appear on the top line of terminal.

Can you tell me how I can fix this.

-------------------------------------------------------------------------
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

my system information
--------------------------------------------------------------------------

**Comment by OptimistLabyrinth** [comment]
![screenshot from 2018-08-14 17-24-05](https://user-images.githubusercontent.com/16411622/44081416-9d01e7c4-9fe9-11e8-8312-f84f27c4fd1b.png)

like this

**Comment by kevbroch** [comment]
Same issue for 
```
cat /etc/redhat-release 
Red Hat Enterprise Linux Workstation release 7.4 (Maipo)
```

**Comment by DDifDEVzero** [comment]
If you want to fix this by now delete following code from the ~/.oh-my-bash/themes/base.theme.sh :

# See if we need to use the overriden version
    if [[ $(fn_exists append_prompt_command_override) ]]; then
       append_prompt_command_override $1
       return
    fi

The developer insert this code because allow the overriding of the prompt setter command, see here:

https://github.com/ohmybash/oh-my-bash/pull/24

habby bashing

**Comment by OptimistLabyrinth** [comment]
@DDifDEVzero 

Thanks! I didn't know that line exists.
