### ISSUE TITLE
Two tabs for showing more results

### ISSUE THREAD

**Issue by RZHSSNZDH** [ohmybash/oh-my-bash#315]
It whould be better to need "two" tabs for showing more results for completion instead of one tab; like bash itself.

**Comment by akinomyoga** [comment]
It is intentionally set [here](https://github.com/ohmybash/oh-my-bash/blob/209ffda0a6df7064d5b68bfa026130346d38486a/lib/shopt.sh#L35-L36). If you would like the default behavior of the plain Bash, you can add the following line at the *end* of `~/.bashrc`.

```bash
bind 'set show-all-if-ambiguous off'
```

**Comment by RZHSSNZDH** [comment]
Oh thank you!
