### ISSUE TITLE
How to check Random Theme

### ISSUE THREAD

**Issue by portfedh** [ohmybash/oh-my-bash#321]
Hi, 
I have my theme set to random. 
If I like the current theme: Is there a way to get the name of the current theme?

**Comment by akinomyoga** [comment]
> If I like the current theme: Is there a way to get the name of the current theme?

With the current version, the theme name is printed on the startup. For example, when the theme `pro` is loaded, the following message is shown.

```bash
[oh-my-bash] Random theme '/path/to/.oh-my-bash/themes/pro/pro.theme.sh' loaded...
chatoyancy: oh-my-bash git:( master → upstream ?:17 ✗ ) $
````

Currently, `oh-my-bash` doesn't provide a way to get the theme name after the startup, but you can run the following command to extract the current theme filename:

```bash
$ (shopt -s extdebug; declare -F _omb_theme_PROMPT_COMMAND | cut -d ' ' -f 3)
```

**Comment by akinomyoga** [comment]
In commit 8451bfa, I have added a variable OMB_THEME_RANDOM_SELECTED. Now the theme name can be checked by the following command:

```bash
$ echo "$OMB_THEME_RANDOM_SELECTED"
```

Also, the startup message now includes the extracted theme name along with the theme filename as

```bash
[oh-my-bash] Random theme 'n0qorg' (/home/murase/.mwg/git/ohmybash/oh-my-bash/themes/n0qorg/n0qorg.theme.sh) loaded...
[chatoyancy] ~/.../ohmybash/oh-my-bash [(master → upstream ?:16*)]»
```

**Comment by portfedh** [comment]
Thank you! Works like a charm.

**Comment by akinomyoga** [comment]
Thanks for checking! I now close the issue.
