### ISSUE TITLE
Adding enviroment variables to .bashrc file

### ISSUE THREAD

**Issue by portfedh** [ohmybash/oh-my-bash#322]
I've added enviroment variables to my .bashrc file

Will these variables be deleted once oh my bash updates?

If so, what is the correct file to save them to preserve them?

I tried in $ .oh-my-bash/custom/aliases

But it did not work correctly.

**Comment by akinomyoga** [comment]
This is a duplicate of #303.

> Will these variables be deleted once oh my bash updates?

No, they will remain. So you can just add variables in `.bashrc`. The update does not change `.bashrc` once `.oh-my-bash` is installed.

However, if you uninstall oh-my-bash and then reinstall it, `.bashrc` will be overwritten by the default `.bashrc`.

> I tried in $ .oh-my-bash/custom/aliases

What do you mean by `$ .oh-my-bash/custom/aliases`? `.oh-my-bash/custom/aliases` is a directory so cannot be executed in the interactive session.

- You need to create a file with an extension `.aliases.bash` or `.aliases.sh` inside the directory and to add the name in the array `aliases` defined in `.bashrc`.
- Or you can just create a file with an extension `.bash` or `.sh` in the directory `.oh-my-bash/custom/lib` (please create the directory if there is not).

**Comment by portfedh** [comment]
Thank you for clarifying. This worked.

**Comment by akinomyoga** [comment]
OK, thanks!
