### ISSUE TITLE
Easy System-Wide Install

### ISSUE THREAD

**Issue by aress31** [ohmybash/oh-my-bash#325]
I managed a `Linux` box **with multiple users** and would like a simple and clean way to install `Oh-My-Bash` **system-wide**. Can an option be added to the installer for that or alternatively the exact instructions added to the `README`?

**Comment by akinomyoga** [comment]
Yeah, maybe it is useful to put them in README or in some other places. If you would like to know the solution as soon as possible, you might take a look at the recipe in AUR: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=oh-my-bash-git (though I personally haven't tested it).

**Comment by aress31** [comment]
Need an easy way, maybe an extra option to the install script to automatically make the installation system-wide for easy provisioning of new systems.

**Comment by akinomyoga** [comment]
Thanks. I'll consider it when I have time.

**Comment by aress31** [comment]
@akinomyoga any update on this ticket?

**Comment by akinomyoga** [comment]
No, actually, the priority of new features is lower than that of the present problems.

**Comment by akinomyoga** [comment]
@aress31 I have supported it in commit 2df8a25. Could you check the behavior? The usage is found in [README](https://github.com/ohmybash/oh-my-bash#system-wide-installation).

**Comment by aress31** [comment]
When you say:

> The Bash startup file .bashrc needs to be manually set up by each user.

Does that mean that we can't have a system wide configuration (i.e., `/etc/bash.bashrc`)?

**Comment by akinomyoga** [comment]
> > The Bash startup file .bashrc needs to be manually set up by each user.
> 
> Does that mean that we can't have a system-wide configuration (i.e., `/etc/bash.bashrc`)?

First of all, even if it is possible, I don't think we should force users to use `oh-my-bash` with a fixed theme and fixed plugins/aliases/completions. The users wouldn't be able to select or change the theme/plugins/aliases/completions If we put the OMB configuration in `/etc/bash.bashrc`.

Next, `/etc/bash.bashrc` is something determined by the distribution and cannot be enabled or changed by Bash compiled with the default configuration. It is only available with a fixed path when the distribution sets it at the compile time of Bash using the compiler flag `CPPFLAGS=-DSYS_BASHRC=/etc/bash.bashrc`. Only a part of distributions sets it, and also the actual path depends on the distribution. I've now checked different distributions: Debian/Ubuntu/OpenSUSE/Arch set `/etc/bash.bashrc`. Solaris/SunOS set `/etc/bash/bashrc`. Fedora/RHEL/CentOS do not set it but instead are letting users manually source `/etc/bashrc` in their `~/.bashrc`. FreeBSD/Minix don't provide it or any other similar mechanism.

Third, if the distribution sets it, usually the file is provided and managed by the package system of the distribution, so I think we should not overwrite it by a third-party package.

**Comment by akinomyoga** [comment]
I had already added the information in the installation message, but in commit c91d1db, I have also added in README how to set it up for each user.

**Comment by akinomyoga** [comment]
@aress31 Do you have any further requests? Can I close the issue?

**Comment by aress31** [comment]
No its ok thanks @akinomyoga !

**Comment by akinomyoga** [comment]
Thanks!
