### ISSUE TITLE
Aliases in directories.sh not overridable

### ISSUE THREAD

**Issue by XeroxDev** [ohmybash/oh-my-bash#329]
Hello!

I've my own `ll` command / alias and want to use it. I tried to override it with a own file in `custom/aliases/custom.aliases.sh` because the example file said this would be possible. But sadly.. No effect.. To be 100% sure the new files are loaded, I restarted the whole bash (logout and reconnect).

Expected Behavior:
`alias ll='exa -lFaBgh --group-directories-first --time-style long-iso --git'`

Current Behavior
`which` -> `alias ls='ls --color=auto'`
`type` -> `ll is aliased to 'ls -lh'`

Is this a bug or intended?

Edit: After moving the file in the root of custom it works

**Comment by akinomyoga** [comment]
> I tried to override it with a own file in `custom/aliases/custom.aliases.sh` because the example file said this would be possible.

Have you added the entry "`custom`" in [the array `aliases` in `.bashrc`](https://github.com/ohmybash/oh-my-bash/blob/a652a77c170b06e60c3e8652e31f6ccf2440a42f/templates/bashrc.osh-template#L71)? An `aliases` file in `$OSH_CUSTOM/aliases` is supposed to be sourced when it is added to the array `alaises`.

**Comment by XeroxDev** [comment]
No. Didn't knew that. Thanks! But I guess I'll let the file in the custom root.
