### ISSUE TITLE
install oh-my-bash without then entering the shell

### ISSUE THREAD

**Issue by CarloLucibello** [ohmybash/oh-my-bash#334]
I'm installing oh-my-bash with the usual 
```
bash -c "$(wget https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh -O -)"
```
inside a bash script which then has some additional commands configuring a remote machine. The execution of the script is interrupted by the oh-my-bash install script opening a new shell. Is there a way to avoid this or to send an exit command to the new shell?

**Comment by akinomyoga** [comment]
Please supply the `--unattended` option:

```bash
bash -c "$(wget https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh -O -)" --unattended
```

**Comment by CarloLucibello** [comment]
Thanks! Should I close the issue or maybe this can be added to the Readme?

**Comment by akinomyoga** [comment]
OK, I have picked the description from the upstream Oh My Zsh (cef755582affbf266e6d81ba6c0e142a690aeefa).

**Comment by CarloLucibello** [comment]
thanks again
