### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by TheGhostboi64** [ohmybash/oh-my-bash#338]
So I just added brew to the plug-ins right?
But after I save it, type in bash, then brew, I get ‘brew: command not found’.
Anyway how to fix this?

**Comment by akinomyoga** [comment]
Could you use the command `brew` before you added the entry `brew` in the array `plugins`?

The plugin `brew` just defines some aliases, which can be used with the command `brew` (see [plugins/brew/README](https://github.com/ohmybash/oh-my-bash/tree/master/plugins/brew) for the detail of aliases), but does not install the command `brew`, i.e., the command `brew` needs to be separately installed.

**Comment by TheGhostboi64** [comment]
no
