### ISSUE TITLE
Layout for themes in the Wiki looks weird

### ISSUE THREAD

**Issue by dundunn** [ohmybash/oh-my-bash#34]
I don't think that's intended. There are no screenshots and the layout doesn't look right. 
https://github.com/ohmybash/oh-my-bash/wiki/Themes

**Comment by JavyMB** [comment]
@nntoan  I can tackle this issue.

**Comment by Kreyren** [comment]
Assigned help wanted assuming that this issue expects screenshots of our themes, adding them myself passively.

**Comment by Israel-Laguan** [comment]
Added #116 to help in this issue

**Comment by nntoan** [comment]
Fixed in #116
