### ISSUE TITLE
Authentication required after upgrade Ubuntu 21.10 -> 22.04

### ISSUE THREAD

**Issue by deyanp** [ohmybash/oh-my-bash#340]
After Ubuntu upgrade every new terminal (Terminator) instance asks me for (sudo) authentication. 

If I comment out the following line in ~/.bashrc then no authentication is required: 

`source $OSH/oh-my-bash.sh`

No authentication was required when opening a new terminal (Terminator) on Ubuntu 21.10 either ..

What could be the issue?

**Comment by akinomyoga** [comment]
Thank you for the report. There seem to be several places in the codebase where the `sudo` command is used. To narrow it down, can you check the following points?

- Which theme do you use? Does it still happen with a simple theme such as `OSH_THEME=minimal`?
- Is the authentication required even with no plugins/aliases/completions (i.e., `completions=();aliases=();plugins=()`)?
- Does the authentication disappear with any of the following settings (before sourcing `$OSH/oh-my-bash.sh`)?

```bash
THEME_SHOW_SUDO=false
THEME_CHECK_SUDO=false
OMB_USE_SUDO=false
```

**Comment by deyanp** [comment]
Thanks for the quick answer @akinomyoga !

Currently I am using

`OSH_THEME="powerline"`

if I comment that line out, or replace `powerline` with `minimal`, then it works without asking for sudo/auth.

`THEME_SHOW_SUDO=false` alone does not help

`THEME_CHECK_SUDO=false` alone **does** solve the problem (with `OSH_THEME="powerline"`)!

`OMB_USE_SUDO=false` alone does not help

Is the solution to my problem `THEME_CHECK_SUDO=false` (keeping the powerline theme which I like)?

**Comment by akinomyoga** [comment]
> OSH_THEME="powerline"

> `THEME_CHECK_SUDO=false` alone **does** solve the problem (with `OSH_THEME="powerline"`)!

Ah, OK. I guess the copy of Oh My Bash you are using is old. Can you update Oh My Bash to the latest version? If you cannot update it or would like to use an old version of Oh My Bash intensionally,

> Is the **proper** solution to my problem `THEME_CHECK_SUDO=false` (keeping the powerline theme which I like)?

would be a valid solution.

**Comment by deyanp** [comment]
Thanks a lot, @akinomyoga , upgraded and all fine now. 

I copied the aliases from the previous .bashrc and started getting an error that the kubectl aliases cannot be found, but then found  https://github.com/ohmybash/oh-my-bash/issues/294#issuecomment-1011990570 in which explains it (aliases were never there). 

Just wondering what is better - put some custom aliases in custom/aliases, or just have my custom aliases directly in the .bashrc file ... I guess it does not matter.
