### ISSUE TITLE
ssh completion -> egrep: empty (sub)expression

### ISSUE THREAD

**Issue by kleinski** [ohmybash/oh-my-bash#346]
Using grep as an alias for egrep leads to "ssh egrep: empty (sub)expression" in the completion of ssh hosts.
I commented the following alias setting in .oh-my-bash/lib/grep.sh out and now the irritating error message is gone:

`#  omb_util_alias grep="egrep ${_omb_grep_options[*]}"`

I suggest leaving it to the user, if grep or egrep shall be used, would be better.

Using bash 5.1.16 on MacOs 12.3.1.

![image](https://user-images.githubusercontent.com/3239736/178987673-5ed44dc3-a5b3-4e01-8711-f9c2ba35f3b4.png)

**Comment by akinomyoga** [comment]
Oh, this is just my mistake I made in #305. This is causing an error with `grep -v ^\|` in [this line](https://github.com/ohmybash/oh-my-bash/blob/e7ca92bde1ac8bb7f07e5df82cb679de95f9cf11/completions/ssh.completion.sh#L23). I pushed a fix e7ca92b. Thank you for the report.
