### ISSUE TITLE
Theme don't work properly

### ISSUE THREAD

**Issue by artelrobotics** [ohmybash/oh-my-bash#349]
powerline theme don't work properly, I've done all configurations like in Readme but result is some strange
![image](https://user-images.githubusercontent.com/99396576/184345111-95e42f28-e3df-4910-800c-fa75ff704206.png)
not like 
![image](https://user-images.githubusercontent.com/99396576/184345162-a6ac1eb6-4152-483b-8e8c-2729ebd5c72e.png)

Here is my .bashrc  conf
case $- in
  *i*) ;;
    *) return;;
esac
export OSH=~/.oh-my-bash
OSH_THEME="powerline"
DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="true"
OMB_USE_SUDO=false
completions=(
  git
  composer
  ssh
  osx
  bundler
  rake
)
aliases=(
  general
)
plugins=(
  git
  bashmarks
)
source "$OSH"/oh-my-bash.sh

**Comment by akinomyoga** [comment]
The above picture is also from Oh My Zsh. Not all the features are ported to Oh My Bash. Which feature do you specifically talk about?
- You need to install and configure a powerline font in your terminal.
- The git information is only shown when the current working directory is under a git repository.
- Syntax highlighting is not supported by Oh My Bash. You might consider using [ble.sh](https://github.com/akinomyoga/ble.sh).

**Comment by artelrobotics** [comment]
instaling fonts helped
sudo apt-get install fonts-powerline

**Comment by RoggeHaj** [comment]
Are there any plans to support syntax highlighting in Oh My Bash?

**Comment by akinomyoga** [comment]
No. See https://github.com/ohmybash/oh-my-bash/issues/157#issuecomment-728376180. You should separately setup both OMB and ble.sh.
