### ISSUE TITLE
Verbose Flag for mkdir in the general alias script doesn't work on OpenBSD

### ISSUE THREAD

**Issue by MARKMENTAL** [ohmybash/oh-my-bash#351]
Hi, first I want to say many thanks for making this tool. I'm currently using ohmybash on OpenBSD and coming from a Linux background it makes my life a lot easier. I noticed that while trying to use the mkdir command i get an error along the lines of an unknown flag of -v. when I try to use the mkdir command.  Upon further inspection I found that the verbose flag doesn't exist for mkdir on OpenBSD, but it is set as a default general alias in ohmybash. Could this verbose flag be removed for future versions to allow for better compatibility with non-Linux Unix-Like OSES?

Thanks,
Mark

**Comment by akinomyoga** [comment]
Thank you for the report. I have pushed a fix 91b36b48a7c6766050889fa684998f4b9f423301. Could you check the behavior?

**Comment by MARKMENTAL** [comment]
Just cloned the new version on  my OpenBSD server and it is working fine, thanks for the speedy update!

> Thank you for the report. I have pushed a fix [91b36b4](https://github.com/ohmybash/oh-my-bash/commit/91b36b48a7c6766050889fa684998f4b9f423301). Could you check the behavior?

**Comment by akinomyoga** [comment]
Thank you for your checking!
