### ISSUE TITLE
_omb_util_command_exists: command not found

### ISSUE THREAD

**Issue by toulousain79** [ohmybash/oh-my-bash#354]
Hello,

After a `git pull`, I get the following error `_omb_util_command_exists: command not found`.

The function does not exist: https://github.com/ohmybash/oh-my-bash/search?p=2&q=_omb_util_command_exists

I also got this error a few times:

`~/.oh-my-bash/aliases/general.aliases.sh: line 36: _omb_util_mktemp: command not found`.

**Comment by akinomyoga** [comment]
Thank you for the report! It doesn't seem to reproduce. I suspect maybe you are using two incompatible versions of oh-my-bash. We need more information to identify the cause. Could you answer the following questions?

- **Q1** How do you configure your `~/.bashrc`?
- **Q2** What is the value of OSH? You can check it by running the following command:

```bash
$ echo "$OSH"
```

- **Q3** Is the function `_omb_module_require` defined?

```bash
$ type _omb_module_require
```

- **Q4** What is the value of `_omb_module_loaded`?

```bash
$ echo "${_omb_module_loaded-(unset)}"
```

**Comment by toulousain79** [comment]
Hello,

It's a mistake on my part, the return from vacations is difficult ....
A plugin was loaded before the loading of Oh-My-Bash.

Regards,
