### ISSUE TITLE
-bash: _omb_alias_general_cp_init: command not found

### ISSUE THREAD

**Issue by msyyces8x95** [ohmybash/oh-my-bash#359]
I did encounter a pretty unusual error message today while running a simple bash command : 
command :  `find "PATH WITH SPACES" -name '*.SOMEEXTENSION' | while read line; do cp "$line" .; done`
result :  multiple `-bash: _omb_alias_general_cp_init: command not found`

I did run the command in a bash session **without OMB** and the command runs fine :(

**Comment by akinomyoga** [comment]
It is supposed to be fixed in the latest master. Which version of OMB do you use? Could you update it to the latest version?

**Comment by msyyces8x95** [comment]
now it works, I did update to version : `f52647d..074fe6f`
