### ISSUE TITLE
Syntax error on unexpected token (myip function)

### ISSUE THREAD

**Issue by lisandrocarmona** [ohmybash/oh-my-bash#364]
As per today, my oh-my-bash started to show a syntax error at file .oh-my-bash/lib/base.sh, line 219. If I comment the function below, the error message disappears.

bash: ~/.oh-my-bash/lib/base.sh: line 219: syntax error on unexpecAs per today, my oh-my-bash started to show a syntax error at file .oh-my-bash/lib/base.sh, line 219. If I comment the function below, the error message disappears.

``` bash: ~/.oh-my-bash/lib/base.sh: line 219: syntax error on unexpected token '(' myip () {' ```

Oh-my-bash offending code:

``` myip () { res=$(curl -s checkip.dyndns.org | grep -Eo '[0-9\.]+') echo -e "Your public IP is: ${_omb_term_bold_green} $res ${_omb_term_normal}" } ```

It appeared on both Arch and openSUSE Tumbleweed, and I have no alias on "myip" if this has any relation with the error. How can I troubleshoot and provide more info on this issue? Thanks.

**Comment by akinomyoga** [comment]
It doesn't reproduce in my environment. Another alias might be interfering. Could you list the aliases by temporarily putting the line `alias >&2` before `source .../oh-my-bash.sh` in `.bashrc`?

**Comment by akinomyoga** [comment]
I tried oh-my-bash in Arch Linux, but the problem still doesn't seem to reproduce.

I have already mentioned it in the previous reply, but could you provide us with the entire list of the aliases defined in your environment when `oh-my-bash.sh` is sourced? You can temporarily rewrite your `~/.bashrc` in the following way so the list of the aliases are printed at the startups of Bash:

```diff
diff --git a/.bashrc b/.bashrc
--- a/.bashrc
+++ b/.bashrc
@@ -91,6 +91,7 @@ plugins=(
 #      plugins+=(tmux-autoattach)
 #  fi

+alias >&2 # debug for GitHub #364
 source "$OSH"/oh-my-bash.sh

 # User configuration

```

Then you can copy and paste the list to here.

**Comment by lisandrocarmona** [comment]
Thank you very much! What was my suspicion you've confirmed: with the command `alias >&2 ` I discovered an alias of zsh that was interfering.
