### ISSUE TITLE
add virtualenv rr theme

### ISSUE THREAD

**Issue by gab-25** [ohmybash/oh-my-bash#372]
hello all, it is possible to add the visualization of the virtual environment in the rr theme

**Comment by gab-25** [comment]
thus fixing the function I was able to add the virtual environment.
function _omb_theme_PROMPT_COMMAND() {
    local user_name="${_omb_prompt_white}\u${_omb_prompt_reset_color}"
    local base_directory="${_omb_prompt_bold_blue}\W${_omb_prompt_reset_color}"
    local GIT_THEME_PROMPT_PREFIX="${_omb_prompt_bold_purple}git:(${_omb_prompt_reset_color}"
    local SVN_THEME_PROMPT_PREFIX="${_omb_prompt_bold_purple}svn:(${_omb_prompt_reset_color}"
    local HG_THEME_PROMPT_PREFIX="${_omb_prompt_bold_purple}hg:(${_omb_prompt_reset_color}"
    local SCM_THEME_PROMPT_SUFFIX="${_omb_prompt_bold_purple})${_omb_prompt_reset_color}"
    local SCM_THEME_PROMPT_CLEAN="${_omb_prompt_bold_green} ✓${_omb_prompt_reset_color}"
    local SCM_THEME_PROMPT_DIRTY="${_omb_prompt_bold_red} ✗${_omb_prompt_reset_color}"
    local arrow="${_omb_prompt_bold_purple}➜${_omb_prompt_reset_color}"

    PS1="${arrow}  ${user_name} ${base_directory} "

    local VIRTUALENV_THEME_PROMPT_PREFIX="${_omb_prompt_bold_purple}vitualenv:(${_omb_prompt_reset_color}"
    local VIRTUALENV_THEME_PROMPT_SUFFIX="${_omb_prompt_bold_purple}) ${_omb_prompt_reset_color}"
    local python_venv; _omb_prompt_get_python_venv
  
    PS1+=${python_venv}

    local scm_info=$(scm_prompt_info)

    PS1+=${scm_info:+$scm_info }
    PS1+=${_omb_prompt_normal}
}

**Comment by akinomyoga** [comment]
I picked the suggestion in PR #400.
