### ISSUE TITLE
Missing terraform completions an `t` alias for terraform

### ISSUE THREAD

**Issue by TechDufus** [ohmybash/oh-my-bash#379]
Can we get tab completion on the `t` alias instead of just terraform? I assume some sort of detection will need to go [here](https://github.com/ohmybash/oh-my-bash/blob/60332ed8fb954f6e6c0af243933e67d570ffc2cc/completions/terraform.completion.sh#L26) to ensure that the `t` alias is defined before leading completion for it....

**Comment by akinomyoga** [comment]
Closing in favor of #380
