### ISSUE TITLE
How can i get a window title bar?

### ISSUE THREAD

**Issue by Radius112** [ohmybash/oh-my-bash#382]
In this video https://sw.kovidgoyal.net/kitty/ it shows the guy having a title bar
but i dont have one for some reason how can i enable it?
btw i am using the latest fedora with bash a terminal

**Comment by alexandre-julien** [comment]
Hello,

What you're asking for has nothing to do with this project. The guy in the
video is either using tmux, a tiling window manager with some customized status
bar or maybe kitty has some integrated one. Your distro is irrelevant as those
tools are distro agnostic. Bash is a shell not a terminal, Kitty on the other
and is a terminal (emulator).

I suggest you take a look at https://github.com/tmux/tmux/wiki for what
you're asking for. It's a great tool, will change your workflow for the
better and is highly customisable.

Please consider closing this issue for the reasons mentioned above.
I'm still willing to help you achieve what you want if you provide me an
email address.
