### ISSUE TITLE
How can I set 24 hour format?

### ISSUE THREAD

**Issue by javlonrahimov** [ohmybash/oh-my-bash#385]
I am using `font` theme with `oh-my-bash`:
```bash
OSH_THEME="font"
```
And current time format is in `am/pm` format:

![Screenshot from 2023-01-08 16-37-16](https://user-images.githubusercontent.com/56770292/211194128-e86a98c2-09cd-449e-922b-fd3ba545e98c.png)

Can I change this to `24 hour` time format? Or even better can I remove it?

**Comment by akinomyoga** [comment]
A way to customize a theme is described in [a wiki page](https://github.com/ohmybash/oh-my-bash/wiki/Customization): you need to copy the theme file and edit it. To remove the time from the `font` theme, you can remove `$(clock_prompt)` in the following line:

https://github.com/ohmybash/oh-my-bash/blob/60332ed8fb954f6e6c0af243933e67d570ffc2cc/themes/font/font.theme.sh#L58

**Comment by javlonrahimov** [comment]
> A way to customize a theme is described in [a wiki page](https://github.com/ohmybash/oh-my-bash/wiki/Customization): you need to copy the theme file and edit it. To remove the time from the `font` theme, you can remove `$(clock_prompt)` in the following line:
> 
> https://github.com/ohmybash/oh-my-bash/blob/60332ed8fb954f6e6c0af243933e67d570ffc2cc/themes/font/font.theme.sh#L58

Thanks, it worked.
