### ISSUE TITLE
Aliases in `.oh-my-bash/lib/bourne-shell.sh` override `.oh-my-bash/custom/aliases/`

### ISSUE THREAD

**Issue by maggick** [ohmybash/oh-my-bash#392]
Aliases in `.oh-my-bash/lib/bourne-shell.sh` override `.oh-my-bash/custom/aliases/`

In particular the  [`ls` alias](https://github.com/ohmybash/oh-my-bash/blob/master/lib/bourne-shell.sh#L63) override my own alias located in `.oh-my-bash/custom/aliases/ls.sh`

I am using kitten so my `$TERM` contain `xterm` that triggered the function to "enable color support of ls and also add handy aliases".

**Comment by akinomyoga** [comment]
Hmm, that's strange. The order of loading is first `.oh-my-bash/lib/bourne-shell.sh` is loaded and then `.oh-my-bash/custom/aliases/ls.sh` is loaded, so it is impossible for `bourne-shell.sh` to overwrite aliases that haven't yet defined and will be defined by `aliases/ls.sh`.

- One possibility is that you haven't specified `ls` in the `aliases` array. To load `aliases/ls.sh`, you need to specify that by including `ls` in [`the aliases array in ~/.bashrc`](https://github.com/ohmybash/oh-my-bash/blob/60332ed8fb954f6e6c0af243933e67d570ffc2cc/templates/bashrc.osh-template#L81-L83).
- Another possibility is that you are using `_omb_util_alias` to define your custom aliases and setting `OMB_DEFAULT_ALIASES=check`. The utility `_omb_util_alias` is used to avoid overwriting existing aliases, so if you use `_omb_util_alias` to define your custom aliases, it wouldn't be defined when there are existing ones. You should use just `alias` for your custom aliases.
- Another possibility is that you are sourcing `.oh-my-bash/custom/aliases/ls.sh` outside the OMB mechanism, e.g., you directly source the file from `~/.bashrc` before sourcing `oh-my-bash.sh`. In that case, you can switch to the OMB mechanism by including `ls` in the `aliases` array in `~/.bashrc`. Or another option is to specify [`OMB_DEFAULT_ALIASES=check`](https://github.com/ohmybash/oh-my-bash/blob/2ce3fff288e7103a2020a689331319b7a407e212/templates/bashrc.osh-template#L58) in `~/.bashrc`.

**Comment by maggick** [comment]
I did not use the `aliases` array.
