### ISSUE TITLE
Completions not working in array format

### ISSUE THREAD

**Issue by 0lzi** [ohmybash/oh-my-bash#397]
My bash completions for brew were not working by adding it to array in exiting format

```
completions=(
       git
       composer
       ssh
       brew
)
```

but work when put in single line array
```
completions=(git composer ssh brew)
```

**Comment by akinomyoga** [comment]
I don't have an idea, but maybe your text editor inserts CR (`\r`) at the end of the line.

What is shown with the following command for the problematic `.bashrc`?

```bash
$ grep brew ~/.bashrc | cat -v
```

**Comment by akinomyoga** [comment]
Glad to hear that! Thank you for letting us know that and closing the issue!
