### ISSUE TITLE
Updated ohmybash now get error when using src

### ISSUE THREAD

**Issue by 0lzi** [ohmybash/oh-my-bash#398]
Before updating using `upgrade_oh_my_bash` src would work fine.

after update

``` 
➜  kellyo aliases git:(master ✓) src
-bash: [: too many arguments
-bash: [: =: unary operator expected
-bash: [: =: unary operator expected
-bash: [: =: unary operator expected
-bash: [: =: unary operator expected
-bash: [: too many arguments
-bash: [: =: unary operator expected
-bash: [: =: unary operator expected
-bash: [: =: unary operator expected
-bash: [: =: unary operator expected
-bash: [: =: unary operator expected
```

**Comment by 0lzi** [comment]
I ran `uninstall_oh_my_bash ` and got the same when the shell reloaded but , reinstalled using `bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"` and ran src and no issue.

**Comment by akinomyoga** [comment]
Thank you! But it doesn't seem to reproduce in my environment. Does it happen again if you run `upgrade_oh_my_bash` again?

**Comment by 0lzi** [comment]
I now get a message about uncommitted changes


```
➜  0lzi ~ upgrade_oh_my_bash
Updating Oh My Bash
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
oh-my-bash: running 'git rebase --abort'...
fatal: No rebase in progress?
There was an error updating.
If you have uncommited changes in '/home/0lzi/.oh-my-bash', please commit, stash or discard them and retry updating.
If you have your own local commits in '/home/0lzi/.oh-my-bash' that conflict with the upstream changes, please resolve conflicts and merge the upstream manually.
```

**Comment by akinomyoga** [comment]
It means that you have edited some of the files. When you want to customize the files inside Oh My Bash, you are supposed to first copy the file into the corresponding directory under `~/.oh-my-bash/custom/...`, and then you can edit the copied file. It is also explained [here](https://github.com/ohmybash/oh-my-bash/wiki/Customization).

For the present problem, if you are familiar with git, you can commit the changes and try upgrading OMB again. If there is any conflicts, you need to resolve them. Or another way is to copy the edited files to the `custom` directory and check out the original files. This will avoid future conflicts.

If you are not familiar with git, maybe the easiest way is to uninstall and reinstall OMB. If you have any changes that you want to keep, 1) you can first check the list of the edited files by running the following command:

```bash
$ cd ~/.oh-my-bash
$ git status
```

2\) You can copy the files that you want to retain the changes to somewhere **outside `~/.oh-my-bash`**, 3) reinstall OMB, 4) move the edited files into `~/.oh-my-bash/custom`.

**Comment by 0lzi** [comment]
I stashed it and pulled and it updated. but the file that it said i edited i didnt touch.

```
➜  0lzi  .oh-my-bash git:(master {1} ✓) git stash pop
Removing templates/bash_profile.osh-template
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    templates/bash_profile.osh-template

no changes added to commit (use "git add" and/or "git commit -a")
Dropped refs/stash@{0} (6f556dda2e730c184bab13dca5d1f7999320c280)
```

**Comment by akinomyoga** [comment]
OK, if you haven't touched it, you can just drop the change and forget about it. Which operating system and toolchains do you use? Depending on the system configuration, there can be some unintended changes. For example, with heterogeneous systems such as the NFS/Samba/CIFS filesystem mounted by different systems, Windows+Cygwin, Windows+MSYS2 (including Git for Windows), and Windows+WSL, sometimes there arise conflicts in the file attributes maintained by different subsystems. This causes the file attribute change recognized by Git.

**Comment by akinomyoga** [comment]
@0lzi What is the current situation? Have you solved your problem? If so, can I close the issue?

**Comment by 0lzi** [comment]
Issue resolved. 

thanks

**Comment by akinomyoga** [comment]
Thanks!

**Comment by 0lzi** [comment]
> I stashed it and pulled and it updated. but the file that it said i edited i didnt touch.
> 
> ```
> ➜  0lzi  .oh-my-bash git:(master {1} ✓) git stash pop
> Removing templates/bash_profile.osh-template
> On branch master
> Your branch is up to date with 'origin/master'.
> 
> Changes not staged for commit:
>   (use "git add/rm <file>..." to update what will be committed)
>   (use "git restore <file>..." to discard changes in working directory)
>         deleted:    templates/bash_profile.osh-template
> 
> no changes added to commit (use "git add" and/or "git commit -a")
> Dropped refs/stash@{0} (6f556dda2e730c184bab13dca5d1f7999320c280)
> ```

related to #407

**Comment by akinomyoga** [comment]
Yes, so it was actually my fault in the introduction of the automatic setup of `~/.bash_profile` suggested by https://github.com/ohmybash/oh-my-bash/issues/302#issuecomment-1416781059. Sorry for the inconvenience.
