### ISSUE TITLE
missing font?

### ISSUE THREAD

**Issue by omid3098** [ohmybash/oh-my-bash#40]
just installed oh-my-bash and my terminal looks like this:

![image](https://user-images.githubusercontent.com/6388730/51035336-f337ca00-15be-11e9-9462-95a055680fb8.png)

is there any missing fonts? if yes, how should I find and install it?

OS: Arch linux x64

Edit: powerline is already installed.

**Comment by hectornguyen** [comment]
Which the current font of your terminal @omid3098 ?

**Comment by nntoan** [comment]
@omid3098 Monospace on Arch linux may not support emoji? The default `oh-my-bash` theme (`font`) using an emoji at your question symbols (an arrow)

**Comment by nntoan** [comment]
I'm using macOS and the default font for the terminal is Menlo.

![screenshot 2019-01-14 17 31 03](https://user-images.githubusercontent.com/3891429/51107899-eadfc900-1822-11e9-9f64-98f1f8faa39b.png)

**Comment by omid3098** [comment]
Changing font to any other fonts did't fix the problem :(

**Comment by Kreyren** [comment]
@omid3098 copypaste the problematic fonts i try to diagnose it

**Comment by omid3098** [comment]
Unfortunately I don't have the same OS on my machine and everything is fine on my current one. 
So maybe we can close this issue.
