### ISSUE TITLE
After update

### ISSUE THREAD

**Issue by astrolavos1998** [ohmybash/oh-my-bash#406]
`[Oh My Bash] Would you like to check for updates? [Y/n]: y   
Updating Oh My Bash
remote: Enumerating objects: 622, done.
remote: Counting objects: 100% (498/498), done.
remote: Compressing objects: 100% (212/212), done.
remote: Total 362 (delta 245), reused 242 (delta 147), pack-reused 0
Receiving objects: 100% (362/362), 101.82 KiB | 868.00 KiB/s, done.
Resolving deltas: 100% (245/245), completed with 85 local objects.
From https://github.com/ohmybash/oh-my-bash
 * branch            master     -> FETCH_HEAD
   496ba61..3a26319  master     -> origin/master
Updating 496ba61..3a26319
Fast-forward
 .shellcheckrc                                       |   1 +
 README.md                                           |  14 +
 aliases/misc.aliases.sh                             |  41 +-
 completions/apm.completion.sh                       |   4 +-
 completions/bundler.completion.sh                   |   4 +-
 completions/capistrano.completion.sh                |   2 +-
 completions/dirs.completion.sh                      |   2 +-
 completions/docker-compose.completion.sh            |  78 +--
 completions/docker-machine.completion.sh            |  46 +-
 completions/docker.completion.sh                    | 258 ++++-----
 completions/drush.completion.sh                     |   4 +-
 completions/gem.completion.sh                       |   6 +-
 completions/gh.completion.sh                        |  22 +-
 completions/git.completion.bash                     |   2 +-
 completions/go.completion.sh                        |   4 +-
 completions/hub.completion.sh                       |  22 +-
 completions/jboss7.completion.sh                    |   6 +-
 completions/projects.completion.sh                  |   2 +-
 completions/rake.completion.sh                      |   2 +-
 completions/salt.completion.sh                      |  12 +-
 completions/sdkman.completion.sh                    |   4 +-
 completions/ssh.completion.sh                       |   2 +-
 completions/test_kitchen.completion.sh              |   4 +-
 completions/tmux.completion.sh                      |   2 +-
 completions/vagrant.completion.sh                   |   6 +-
 completions/virtualbox.completion.sh                |  16 +-
 lib/base.sh                                         | 312 +++++------
 lib/bourne-shell.sh                                 |   4 +-
 lib/grep.sh                                         |   2 +-
 lib/mo.sh                                           |  48 +-
 lib/omb-deprecate.sh                                |   6 +-
 lib/omb-prompt-base.sh                              |  13 +-
 lib/omb-prompt-colors.sh                            |  12 +-
 lib/shopt.sh                                        |  28 +-
 lib/spinner.sh                                      |   6 +-
 lib/utils.sh                                        |  50 +-
 oh-my-bash.sh                                       |  12 +-
 plugins/battery/battery.plugin.sh                   |  10 +-
 plugins/fasd/fasd.plugin.sh                         |   4 +-
 plugins/git/git.plugin.sh                           |  14 +-
 plugins/kubectl/kubectl.plugin.sh                   |   2 +-
 plugins/nvm/nvm.plugin.sh                           |   4 +-
 plugins/tmux-autoattach/tmux-autoattach.plugin.sh   |   4 +-
 templates/bashrc.osh-template                       |   6 +-
 themes/absimple/absimple.theme.sh                   | 319 +----------
 themes/agnoster/README.md                           |   8 +-
 themes/agnoster/agnoster.theme.sh                   | 610 +++++++++++++--------
 themes/axin/axin.theme.sh                           |  49 +-
 themes/binaryanomaly/binaryanomaly.theme.sh         |   4 +-
 themes/bobby/bobby.theme.sh                         |   2 +-
 themes/brainy/brainy.theme.sh                       |  44 +-
 themes/brunton/brunton.theme.sh                     |   6 +-
 themes/cupcake/cupcake.theme.sh                     |   4 +-
 themes/demula/demula.theme.sh                       |  10 +-
 themes/doubletime/doubletime.theme.sh               |   8 +-
 themes/dulcie/dulcie.theme.sh                       |   6 +-
 themes/duru/duru.theme.sh                           |   6 +-
 themes/emperor/emperor.theme.sh                     |   2 +-
 themes/font/font.theme.sh                           |   4 +-
 themes/gallifrey/gallifrey.theme.sh                 |   4 +-
 themes/garo/garo.theme.sh                           |  18 +-
 themes/half-life/half-life.theme.sh                 |   4 +-
 themes/hawaii50/hawaii50.theme.sh                   |   4 +-
 themes/luan/luan.theme.sh                           |  25 +-
 themes/mairan/mairan.theme.sh                       |  12 +-
 themes/minimal/minimal.theme.sh                     |   2 +-
 themes/modern-t/modern-t.theme.sh                   |   6 +-
 themes/modern/modern.theme.sh                       |   6 +-
 themes/nwinkler/nwinkler.theme.sh                   |   2 +-
 .../nwinkler_random_colors.theme.sh                 |   2 +-
 themes/pete/pete.theme.sh                           |   2 +-
 .../powerline-multiline.theme.sh                    |   2 +-
 themes/powerline-naked/powerline-naked.theme.sh     |   2 +-
 themes/powerline-plain/powerline-plain.theme.sh     |   2 +-
 themes/powerline/powerline.theme.sh                 |   2 +-
 themes/pure/pure.theme.sh                           |   4 +-
 themes/pzq/pzq.theme.sh                             |  15 +-
 themes/rainbowbrite/rainbowbrite.theme.sh           |   2 +-
 themes/rana/rana.theme.sh                           |  12 +-
 themes/rjorgenson/rjorgenson.theme.sh               |  12 +-
 themes/rr/rr.theme.sh                               |  33 +-
 themes/sexy/sexy.theme.sh                           |  53 +-
 themes/sirup/sirup.theme.sh                         |   7 +-
 themes/slick/slick.theme.sh                         |  10 +-
 themes/tonka/tonka.theme.sh                         |   8 +-
 themes/tylenol/tylenol.theme.sh                     |   4 +-
 themes/vscode/vscode.theme.sh                       |   4 +-
 themes/zork/zork.theme.sh                           |  12 +-
 tools/bash-preexec.sh                               |  22 +-
 tools/check_for_upgrade.sh                          |   5 +-
 tools/git-completion.bash                           |  12 +-
 tools/install.sh                                    |  71 +--
 tools/uninstall.sh                                  |   7 +-
 tools/upgrade.sh                                    |  43 +-
 94 files changed, 1272 insertions(+), 1344 deletions(-)
 create mode 100644 .shellcheckrc
         __                          __               __  
  ____  / /_     ____ ___  __  __   / /_  ____ ______/ /_ 
 / __ \/ __ \   / __ `__ \/ / / /  / __ \/ __ `/ ___/ __ \
/ /_/ / / / /  / / / / / / /_/ /  / /_/ / /_/ (__  ) / / /
\____/_/ /_/  /_/ /_/ /_/\__, /  /_.___/\__,_/____/_/ /_/ 
                        /____/                            
Hooray! Oh My Bash has been updated and/or is at the current version.
To keep up on the latest news and updates, follow us on GitHub: https://github.com/ohmybash/oh-my-bash
oh-my-bash (module_require): module 'plugin:bundler' not found.
oh-my-bash (module_require): module 'plugin:osx' not found.
oh-my-bash (module_require): module 'plugin:rake' not found.
oh-my-bash (module_require): module 'plugin:ruby' not found.
`
What happen with plugin: bundler, osx, rake, ruby ?

**Comment by akinomyoga** [comment]
Dup #324
