### ISSUE TITLE
Completion for custom Git commands

### ISSUE THREAD

**Issue by RoggeHaj** [ohmybash/oh-my-bash#411]
Hi,

I have a question on whether it's possible to enable completion for home brew bash functions? Currently we have a regular bash function

```bash
function gcb () {
    _branch=${1}
    git checkout ${_branch} || return -1
    git submodule status && git submodule update --init

   # Other stuff goes here...

    return 0

}
```
Code that hides under "Other stuff" makes it difficult to implement as a regular git alias. What I want to achieve is to have completion similar to what I get from

```bash
git checkout <tab>
```

I'm totally happy with a solution to this specific case, but if there's a more general way to set things up it's even better.

**Comment by akinomyoga** [comment]
That is explained in the code comments of the upstream git-completion file.

> [git/git - d15644fe `contrib/completion/git-completion.bash`:32-36](https://github.com/git/git/blob/d15644fe0226af7ffc874572d968598564a230dd/contrib/completion/git-completion.bash#L32-L36)
> ```bash
> # If you have a command that is not part of git, but you would still
> # like completion, you can use __git_complete:
> #
> #   __git_complete gl git_log
> #
> ```

So I guess something like the following would work:

```bash
__git_complete gcb git_checkout
```

Note: The above line needs to be put in `.bashrc` after `source /path/to/oh-my-bash.sh`. Also, please do not forget to include `git` in the `completions` array.
