### ISSUE TITLE
Git completion is not compatible with centos7

### ISSUE THREAD

**Issue by shelfofclub** [ohmybash/oh-my-bash#415]
Currently oh my bash searches `git-core/contrib/completion/git-completion.bash`
https://github.com/ohmybash/oh-my-bash/blob/ec7efa5628f6d087bc1a68cb11c23704798d00ee/completions/git.completion.bash#L17

However, in centos7, there is no `/usr/share/bash-completion/completions/git`, but it has `/usr/share/doc/git-1.8.3.1/contrib/completion/git-completion.bash`.

**Comment by akinomyoga** [comment]
@shelfofclub Thank you for the report. I have pushed a fix in 70e0787. Could you check it?

**Comment by shelfofclub** [comment]
@akinomyoga It doesn't work.
The `file` is `/share/bash-completion/completions/git` or `/usr/share/bash-completion/completions/git`.

And it seems that you use prefix before defining it.

**Comment by akinomyoga** [comment]
Ah, sorry, you are right. It seemed to work in my local testing, but it just picked up `prefix` of the previous loop. Also, I now noticed that your reported path contains `doc` after `share`. I also added the possible path of `doc`. I pushed commit 96f6e00. Could you check it again?

**Comment by shelfofclub** [comment]
@akinomyoga It works!👍

**Comment by akinomyoga** [comment]
Thanks for reporting and checking!
