### ISSUE TITLE
Issue with autocomplete with vim

### ISSUE THREAD

**Issue by RaZeSloth** [ohmybash/oh-my-bash#416]
When trying to autocomplete with vim, I am getting the following error:
```
bash: syntax error near unexpected token `('
```

Started happening after the recent update.

**Comment by akinomyoga** [comment]
Thank you for the report. I could reproduce the problem. I fixed it in eb1ea3e. @RaZeSloth @D4ryl00 Could you check if the problem is fixed in the latest version?

**Comment by D4ryl00** [comment]
LGTM, thanks :+1:

**Comment by akinomyoga** [comment]
Thanks!
