### ISSUE TITLE
Agnoster issue after updating

### ISSUE THREAD

**Issue by edoardottt** [ohmybash/oh-my-bash#417]
Hi, sorry if this is a problem easily fixable but I don't know how oh-my-bash works.

After updating oh-my-bash (agnoster theme) I have an extra green triangle in the prompt that should be there only for git branch info but it's there even blank.
![Screenshot from 2023-03-14 09-10-06](https://user-images.githubusercontent.com/35783570/224936474-09808d10-1f08-4bd0-b5c1-10222fc37246.png)

Moreover, the console prints weird git-related output every time I execute a command (but even with a simple ENTER too)
![Screenshot from 2023-03-14 09-11-52](https://user-images.githubusercontent.com/35783570/224936826-2f91d2ec-2a9c-4df1-be18-51a53ec7768a.png)

**Comment by akinomyoga** [comment]
Maybe, do you define a command `hg` as something different from Mercurial's `hg`?

The upstream [`speedenator/agnoster-bash`](https://github.com/speedenator/agnoster-bash) added the support for the version control system Mercurial (`hg`) (https://github.com/speedenator/agnoster-bash/commit/d06166724cc9d6e5cd59a0000f9dd1292db50fe0), and we recently imported the change from the upstream (8c2f1d5049d98c5fe9de6bea827d9d6a4c12a333). When there is a command `hg`, the Agnoster theme considers it to be Mercurial's CLI command just like Git's `git`.

**Comment by edoardottt** [comment]
oh yes! I use `alias hg="history | grep -i $1"`.

Is there a way to disable mercurial hg? Cuz I know I won't use that, if not I'll rename hg to something else ..

Thanks for your fast answer !!!!

**Comment by akinomyoga** [comment]
I think there are many ways to modify it. For example, you can overwrite `prompt_hg` with an empty function after `source "$OSH/oh-my-bash.sh"` in `~/.bashrc`.

```bash
# add this line after "source oh-my-bash.sh" in bashrc
function prompt_hg { return 0; }
```

**Comment by akinomyoga** [comment]
> I use `alias hg="history | grep -i $1"`.

By the way, 1) `$1` in `alias hg="history | grep -i $1"` would be expanded at the defining time of the alias, but not the expansion time of the alias, so you are actually defining an alias `alias hg='history | grep -i '`. The space at the end of the alias definition would induce another alias expansion for the next argument. 2) Even if the alias is defined as `alias hg='history | grep -i $1'` (which I think would be your intent), Bash doesn't support `$1` in the alias definition like Zsh. The alias will be expanded to the literal `$1` in Bash.

**Comment by edoardottt** [comment]
```
function prompt_hg { return 0; }
```
is working super fine. Thanks !!!

I'm using 
```
alias hg="history | grep -i $1"
```
inside .bashrc and I can confirm is working properly ($1 being replaced to the first argument)

**Comment by akinomyoga** [comment]
> I'm using
> 
> ```
> alias hg="history | grep -i $1"
> ```
> 
> inside .bashrc and I can confirm is working properly ($1 being replaced to the first argument)

The above might work in most cases, but that is not working in the way that you expect. As you write it in `~/.bashrc` where `$1` is normally an empty string, so I think the alias definition becomes `alias hg='history | grep -i '`. You can check the resulting definition of the alias with the following command. What is shown with this command?

```bash
$ alias hg
```

**Comment by edoardottt** [comment]
Thanks for the explanation. I didn't know that!!!

When using `alias hg="history | grep -i $1"` i get this

```
$> alias hg
alias hg='history | grep -i '
```

and in fact I also have an alias mapping "python" to "python3", executing `hg python`, I search for python3 and not python (alias expanded)...

with single quotes I got this working properly..

Thank u so much !!!

**Comment by akinomyoga** [comment]
OK, let me close the issue since the original issue seems to have been solved.
