### ISSUE TITLE
nano alias in .oh-my-bash/aliases/general.aliases.sh no longer working on macOS

### ISSUE THREAD

**Issue by randvmbone** [ohmybash/oh-my-bash#419]
macOS replaced nano with pico and pico doesn't support -W. eliminating this flag allows 'nano somefile' to work, otherwise full path '/usr/bin/nano somefile' is required.

apparently also fixes an issue with .bashrc causing error and preventing session from starting

**Comment by akinomyoga** [comment]
Thanks for the report. The option `-W` seems to be used to truncate trailing spaces at the end of lines. I decided to define the alias only when `nano --help` contains `-W`. I pushed a fix 5fd472f.

There seems to have been a similar report for another option `-$` in the past (#20). At that time, we just removed the option (#25).
