### ISSUE TITLE
incompatible with bash 5.0.0

### ISSUE THREAD

**Issue by beardedeagle** [ohmybash/oh-my-bash#43]
I am unable to install oh-my-bash on my Mac Book Pro 2018 running Mac OS X 10.14.2:
```
REDACTED:~ REDACTED$ brew info bash
bash: stable 5.0.0 (bottled), HEAD
Bourne-Again SHell, a UNIX command interpreter
https://www.gnu.org/software/bash/
/usr/local/Cellar/bash/5.0.0 (150 files, 9.4MB) *
  Poured from bottle on 2019-01-17 at 13:29:42
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/bash.rb
==> Options
--HEAD
	Install HEAD version
==> Caveats
In order to use this build of bash as your login shell,
it must be added to /etc/shells.
==> Analytics
install: 26,405 (30 days), 51,296 (90 days), 204,628 (365 days)
install_on_request: 20,456 (30 days), 40,924 (90 days), 158,502 (365 days)
build_error: 0 (30 days)
REDACTED:~ REDACTED$ which bash
/usr/local/bin/bash
REDACTED:~ REDACTED$ bash --version
GNU bash, version 5.0.0(1)-release (x86_64-apple-darwin18.2.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
REDACTED:~ REDACTED$ sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
Error: Bash 4 required for Oh My Bash.
Error: Upgrade Bash and try again.
```

**Comment by beardedeagle** [comment]
Belay the issue, I fixed it by following running this command:
```
bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
```
Which I found here: https://github.com/ohmybash/oh-my-bash/issues/27#issuecomment-425317107

Maybe the README should be updated?

**Comment by beardedeagle** [comment]
I was unable to get oh-my-bash working with bash 5.0 in the end. It would not open a session. I had to remove it to get sessions to launch again.

**Comment by Kr0n0** [comment]
I was able to install it with Bash 5.0 by downloading the install.sh file and modifyng the bash_major_version check.

10:38:46 Kr0n0@Kr0n0s-MBP ~ → bash --version
GNU bash, versión 5.0.0(1)-release (x86_64-apple-darwin18.2.0)
Copyright (C) 2019 Free Software Foundation, Inc.
Licencia GPLv3+: GPL de GNU versión 3 o posterior <http://gnu.org/licenses/gpl.html>

**Comment by nntoan** [comment]
@Kr0n0 @beardedeagle It will be fixed in #39

**Comment by nntoan** [comment]
Closed as #39 merged to master.

**Comment by ctrngk** [comment]
please fix this under the **Basic Installation** section in the main page

**Comment by Aisuko** [comment]
I hit the same issue, thanks for your solution help me out.

**Comment by myb0420** [comment]
> I hit the same issue, thanks for your solution help me out.

Same here. Would love to see this info baked into the main page to avoid others needing to google and find this thread (which they will hopefully do)

**Comment by beakish** [comment]
hmm, its closed, but persists apparently BASH_VERSION isnt exported, with the latest bash i guess.

people still facing issues, quick hack, ```export BASH_VERSION="anythinghere"```

**Comment by WarrenWongCodes** [comment]
This was great. 

For anyone who comes across, this works for bash v5.

bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

**Comment by holynakamoto** [comment]
> export BASH_VERSION="anythinghere"
bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"

tried both still not seeing the theme when I pull up a new prompt

**Comment by holynakamoto** [comment]
https://user-images.githubusercontent.com/407440/127775016-9c607632-fc68-47fa-b32a-0076211ea1a0.mov
