### ISSUE TITLE
Error message when opening bash from xfce4-terminal

### ISSUE THREAD

**Issue by developer1105** [ohmybash/oh-my-bash#437]
This message appears everytime bash is launched from xfce4-terminal:

```cat: invalid option -- 'a'```
```Try 'cat --help' for more information.```

**Comment by akinomyoga** [comment]
As far as I search in the repository, oh-my-bash (OMB) does not contain `cat -a`.

What is the Bash version?

```bash
$ echo "$BASH_VERSION"
```

Can you get the log by the following steps?

1. Add the following lines at the top of `~/.bashrc`

```bash
exec 9>~/omb-debug.txt
PS4='+($BASH_SUBSHELL)${BASH_SOURCE[0]-(global)}:$LINENO${FUNCNAME:+($FUNCNAME)}[$?] '
BASH_XTRACEFD=9
set -x
```

2. Open a new instance of xfce4-terminal
3. Close the opened terminal by running `exit`
4. The file `~/omb-debug.txt` is created, so attach the file in a reply to this Issue.
5. The lines added in step 1 can be removed.

**Comment by developer1105** [comment]
Well, the bash version (as informed by the environment variable) is: ```5.1.4(1)-release```

I am currently using Peppermint Linux distro based on Devuan.

The debug is quite long:
[omb-debug.txt](https://github.com/ohmybash/oh-my-bash/files/11267547/omb-debug.txt)

I disabled git completion and the error disappeared (there was a line ```cat -aP git``` in the debug)

**Comment by akinomyoga** [comment]
Thank you for the debug log. According to the provided log, the affected line is the following:

https://github.com/ohmybash/oh-my-bash/blob/255bacacb503c2a6a507a58257ca7cd3219bb11d/completions/git.completion.bash#L6

So, `type -aP git` is transformed into `cat -aP git` in your environment. I suspect an alias is defined for `type`. Then, I find the following line in the log file:

```
++++(0)/home/allein/.bash_aliases:7(source)[0] alias type=cat
```

This means that an alias that replaces `type` with `cat` is defined in `~/.bash_aliases:7`. The `type` command is actually an important Bash builtin command, so I strongly recommend not changing the meaning of `type` in Bash or in POSIX shells. There are still many other places where the `type` builtin is used in the codebase. Even if they do not output errors to the terminal, it would cause unexpected behaviors.

**Comment by developer1105** [comment]
Ok. I have disabled the 'type' alias in my config.
This issue can be marked as closed.
