### ISSUE TITLE
agnoster theme not present

### ISSUE THREAD

**Issue by rpotter12** [ohmybash/oh-my-bash#45]
when changing `OSH_THEME="agnoster"` the output was
![screenshot from 2019-01-30 21-56-09](https://user-images.githubusercontent.com/34352567/51996008-f1846680-24d9-11e9-8f82-9bbb2cf4171f.png)

**Comment by mosaic141688** [comment]
I have the same issue

**Comment by nntoan** [comment]
Because there is no theme name `agnoster` in the `themes`. The README and the WIKI are not up-to-date.

**Comment by JavyMB** [comment]
This is not an issue, is just that is not in the themes folder, 
I can help creating a list of themes with screenshots so you can choose between different available options in oh-my-bash

**Comment by rpotter12** [comment]
@JavyMB I know it's not an issue but since the theme is not present in the project so we need to create it.

Cheers!!

**Comment by JavyMB** [comment]
@rpotter12  cool, We can collaborate and create a better Themes documentation 
🎉

**Comment by rpotter12** [comment]
@nntoan @JavyMB I found a similar agnoster theme https://github.com/speedenator/agnoster-bash. We can use this theme.
