### ISSUE TITLE
lesspipe in gentoo differs from ubuntu

### ISSUE THREAD

**Issue by wingedfox** [ohmybash/oh-my-bash#46]
Hello,

`lesspipe` available in gentoo does not export vars and eval fails with error
```
$ [ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/bash lesspipe)"
bash: syntax error near unexpected token `newline'
```

**Comment by Kreyren** [comment]
Duplicate of https://github.com/ohmybash/oh-my-bash/issues/46

**Comment by Kreyren** [comment]
```bash
rogisek / #  [ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/bash lesspipe)"
bash: syntax error near unexpected token `newline'
```

Same issue on my gentoo

**Comment by Kreyren** [comment]
@wingedfox && @Cowboy0 requesting testing for #74

**Comment by Kreyren** [comment]
Assigned P2 since this is compatibility for Gentoo and simmilar likely to occur in stable release soon.

**Comment by AguilarSolutions** [comment]
Hello!
Congratulations for this awesome project.
I'm a gentoo user and facing this problem with `lesspipe`
Please, is there any update to solve this issue?

**Comment by marshall-mcmullen** [comment]
I modified `~/.oh-my-bash/lib/bourne-shell.sh` and just commented out `[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"`. I have no idea what impact that will have but the problem went away ;-)

**Comment by holmofy** [comment]
Has this problem been solved?

**Comment by IPlayZed** [comment]
> Has this problem been solved?

No, this still persists.
