### ISSUE TITLE
Uninstall script broken

### ISSUE THREAD

**Issue by norahqueen** [ohmybash/oh-my-bash#461]
https://github.com/ohmybash/oh-my-bash/blob/9c9c92bf3121948f1e2683394536e6349efecdc1/tools/uninstall.sh#L38C82-L38C109

I got it to work by changing this line to 
read -r ${BASH_VERSION:+-p} -p "Are you sure you want to remove Oh My Bash? [y/N] " _omb_uninstall_confi ration

**Comment by akinomyoga** [comment]
Thanks for the report. I pushed a fix 06b459e.
