### ISSUE TITLE
Problems immediately after installation

### ISSUE THREAD

**Issue by mmadrono** [ohmybash/oh-my-bash#469]
the error is as follows: 

source .bashrc
: command not found
bash: .bashrc: line 6: syntax error near unexpected token `$'in\r''
'ash: .bashrc: line 6: `case $- in

![image](https://github.com/ohmybash/oh-my-bash/assets/88772930/22239a43-400d-41f6-98af-26affb98d410)

**Comment by akinomyoga** [comment]
duplicate of #253

Git for Windows has an issue in its default setting of the newline treatment. You should change the setting as follows:

```bash
$ git config --global core.autocrlf false

or

$ git config --global core.autocrlf input
```

After that, you need to reinstall OMB.

**Comment by mmadrono** [comment]
thank you very much, it worked
