### ISSUE TITLE
how to highlight folders, scripts etc

### ISSUE THREAD

**Issue by RicoSpm** [ohmybash/oh-my-bash#47]
Hi,
is it possible to highlight folders, scripts (python, bash, perl, ruby, etc) with different fonts?

Thank you,
Riccardo

**Comment by Kreyren** [comment]
Not possible afaik

**Comment by Kreyren** [comment]
Assigned P4 since this is question.

**Comment by Kreyren** [comment]
Referencing https://unix.stackexchange.com/a/94505 which should fix this issue.
>  the color settings can be modified via dircolors. A list of the different coloring settings can be accessed with dircolors --print-database.
> 
> Each line of output, such as BLK 40;33;01, is of the form:

@RicoSpm Let me know if you need help i will reopen this issue.
