### ISSUE TITLE
oh-my-bash makes autocomplete in taskwarrior go wrong

### ISSUE THREAD

**Issue by JVAQUEROM** [ohmybash/oh-my-bash#471]
In normal bash, with taskwarrior, I get autocompletion like:

```
> task pro:[tab]
myproject otherproject

> task pro:m[tab]
> task pro:myproject
```

However, with oh-my-bash, I get this

```
> task pro:[tab]
myproject otherproject

> task pro:m[tab]
> task myproject
```

So oh-my-bash autocompletion removes the "pro:" part needed by taskwarrior.

**Comment by gvlachos-au** [comment]
Also having the same issue here.

**Comment by uncapped1599** [comment]
Just upgraded to latest version and can confirm this issue has been fixed, at least for rclone. Thanks for all the hard work!

**Comment by JVAQUEROM** [comment]
I just checked and for taskwarrior the problem is still there :cry:

**Comment by akinomyoga** [comment]
Thanks for the additional information. It might depend on the situation. I cannot actually reproduce the problem in my environment. Could you give us the result of the following command after you see the problem?

```bash
$ task pro:m[TAB]  # <-- please attempt the problematic completion
$ task myproject   # <-- confirm that the problem happened. You can discard this line by C-c.
$ complete -p task # <-- Q. In the same session, what is the output of this command?
```

**Comment by JVAQUEROM** [comment]
thanks @akinomyoga. I confirm that the problem is persistent.

```
$ complete -p task # <-- Q. In the same session, what is the output of this command?
complete -o nospace -F _task task
```

Additional information: in my system, completion did not work out of the box, I had to create this symlink: `/usr/share/bash-completion/completions/task -> /usr/share/bash_completion.d/task.sh`

**Comment by akinomyoga** [comment]
Thank you! That means that with Oh My Bash (OMB), a completion setting located in `/usr/share/bash_completion.d/task.sh` is used. I'm also interested in the working case. You have written that the completion seems to work in the normal Bash (without OMB). What is the result of the following command in the normal Bash?

```bash
$ complete -p task
```

**Comment by JVAQUEROM** [comment]
I get this:

```
$ complete -p task
complete -o nospace -F _task task
```

which is the same as for oh-my-bash...

**Comment by akinomyoga** [comment]
@JVAQUEROM Can you check if it is fixed in the branch of #480?

**Comment by JVAQUEROM** [comment]
It works! Thank you!

**Comment by akinomyoga** [comment]
Thanks!

**Comment by epinoia-au** [comment]
Thanks for fixing this  :heart:
