### ISSUE TITLE
New Tab opens on home directory

### ISSUE THREAD

**Issue by brayo-pip** [ohmybash/oh-my-bash#472]
When I clicked on a new tab before installing oh-my-bash the new terminal would inherit the directory of the previous terminal that I launched the new tab from. Now all new tabs open at the home directory. I wish to get the previous behavior back but still keep using oh-my-bash

**Comment by RobLoach** [comment]
Sounds like something that should likely be handled in your terminal emulator, not oh-my-bash.

**Comment by brayo-pip** [comment]
I have since switched emulators, but the behaviour persists was using `gnome terminal` now using `kitty` can confirm it's emulator independent.

**Comment by RobLoach** [comment]
Good to hear. Sounds like we can close this one then. How's Kitty, btw? I haven't used it before.

**Comment by akinomyoga** [comment]
The original report seems to say OMB affects the behavior. Even if it is terminal-dependent, that shouldn't happen unless there is a reason. Why does this behavioral change happen? I don't have an idea. Does anyone have any idea?

**Comment by brayo-pip** [comment]
Just removed omb, checked and it does not affect it anyway. Must have been using vs code terminal emulator so much I thought it was the default behaviour on my terminal emulator. Thanks everyone

**Comment by brayo-pip** [comment]
> Good to hear. Sounds like we can close this one then. How's Kitty, btw? I haven't used it before.

You will love it very snappy, great image rendering.
