### ISSUE TITLE
powerbash10k invokes Sudo

### ISSUE THREAD

**Issue by sahiljhawar** [ohmybash/oh-my-bash#490]
I am using `oh-my-bash` on my university cluster. I recently changed the them to `powerbash10k`. Some of the machines shows the following everytime I press enter, while some machines not showing this
```bash
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.
```

Somehow `powerbash10k` is invoking `sudo`

**Comment by akinomyoga** [comment]
Did you check [README](https://github.com/ohmybash/oh-my-bash#disable-internal-uses-of-sudo)?

**Comment by sahiljhawar** [comment]
I read. Must have skimmed through it. Thanks though :))

**Comment by sahiljhawar** [comment]
@akinomyoga Even after setting `OMB_USE_SUDO=false` sudo is invoked
