### ISSUE TITLE
Bashmarks Issues Saving Directories

### ISSUE THREAD

**Issue by McPrescott** [ohmybash/oh-my-bash#50]
Upon installation, the bashmarks plugin has been behaving incorrectly in strange ways; strange enough that actually showing the behavior will be much easier than attempting to use prose exclusively.

In the following screenshot, bashmarks begins with no bookmarks. As is demonstrated, when bashmarks has one or more bookmarks saved, a `cannot overwrite existing file` message is shown.

![ohmybash oh-my-bash 01](https://user-images.githubusercontent.com/20735042/56549282-99d92280-653f-11e9-8f49-df6550d8492d.png)

Attempting as best I can to describe the incorrect behavior observed:

  1. A `cannot overwrite existing file` error message is shown when saving a 
     bookmark with one or more existing bookmarks.
  2. The `home` bookmark is either never saved, or is deleted for an unknown
     reason.
  3. After saving `home` for the second time, the behavior seems to normalize,
     sauf the aforementioned error message.

There are however, more issues. I've encountered another after starting a new instance of bash; this time the `media` bookmark is deleted.

![ohmybash oh-my-bash 02](https://user-images.githubusercontent.com/20735042/56549954-7c0cbd00-6541-11e9-8e19-2b3fd68c2bc0.png)

Based on these observations, it seems that the issue is related to the implementation of bookmark saving, especially that involving the temporary files (`/tmp/bashmarks.6oXbma`, `/tmp/bashmarks.kJ0zFh`, et cetera, in the examples provided).

**Comment by idavydov** [comment]
I think it's because you have `set -C` in your `.bashrc` file.

With this flag bash won't overwrite an existing file.

In the function `_purge_line` I have corrected this line:
```bash
        # purge line
        sed "/$2/d" "$1" > "$t"
```

To this (note an extra `|` character):
```bash
        # purge line
        sed "/$2/d" "$1" >| "$t"
```

And it seems to work for me.

**Comment by jasonverbeek** [comment]
the issue is in lib/shopt.sh.
It enables contains `set -o noclobber` which prevents overwriting files using > unless you replace it with >|.

Bashmark probably uses `>` in their script to write updates.
