### ISSUE TITLE
Anyon with the same error? Theme sexy 

### ISSUE THREAD

**Issue by cbxcvl** [ohmybash/oh-my-bash#512]
bash: command substitution: line 1: syntax error near unexpected token `)'
bash: command substitution: line 1: `[[ -n $(_omb_prompt_git branch 2> /dev/null) ]] && echo " on ")'
bash: command substitution: line 1: syntax error near unexpected token `)'
bash: command substitution: line 1: `parse_git_branch)'
$

**Comment by cbxcvl** [comment]
I found a fix

replace the original PS1 line with the following code:

```bash
local git_branch
git_branch=$(parse_git_branch)
local git_info
[[ -n $(_omb_prompt_git branch 2> /dev/null) ]] && git_info=" on "
PS1="$python_venv${MAGENTA}\u ${WHITE}at ${ORANGE}\h ${WHITE}in ${GREEN}\w${WHITE}${git_info}${PURPLE}${git_branch}${WHITE}\n\$ ${RESET}"

**Comment by akinomyoga** [comment]
We received similar reports from the users of Git for Windows. Bash distributed with old versions of Git for Windows seems to have a bug. 

If you use Git for Windows, what is the version of Git for Windows in your system? You can update Git for Windows to the latest version.
