### ISSUE TITLE
cannot update .ohmybash

### ISSUE THREAD

**Issue by tokisuno** [ohmybash/oh-my-bash#525]
![image](https://github.com/ohmybash/oh-my-bash/assets/85533116/f62e30f7-398d-479f-a594-a57bb6f0fb15)
Any advice?

**Comment by akinomyoga** [comment]
The directory `~/.oh-my-bash` is a git repository, and the updating is performed by `git pull`. A conflict can happen if you have any changes in `~/.oh-my-bash`. This time, you seem to have uncommitted changes. As the red text explains, you need to commit, stash, or discard the uncommitted changes.

You can go into the directory by `cd ~/.oh-my-bash` and run `git status` to see the current status. To check the changes, run `git diff`. To check the staged changes, run `git diff --cached`.

- To commit all the uncommitted changes, for example, you can run `git add -u` and `git commit -m '<some message to describe the change>'` in the directory `~/.oh-my-bash`.
- To stash the changes to later apply them, you can run `git stash` in the directory `~/.oh-my-bash`.
- To discard the uncommitted changes and revert them to the original Oh My Bash, you can run `git reset --hard` in the directory `~/.oh-my-bash`.
