### ISSUE TITLE
Allow for a way to not alter bash files directly, but to make changes that can be sourced

### ISSUE THREAD

**Issue by Steve973** [ohmybash/oh-my-bash#533]
I read through all of the instructions, and unless I missed it, it doesn't seem like we can instruct oh-my-bash to write the changes that it normally writes to .bashrc to some other file.  I would like to leave my .bashrc (mostly) unedited, except to add a line to source another script.  That way, oh-my-bash updates can occur purely to oh-my-bash files, and it won't overwrite other changes that we make to .bashrc.  I will often decline to perform oh-my-bash updates so that I don't have to go back and re-edit my .bashrc.

**Comment by akinomyoga** [comment]
I'm now busy. If you are a *power user* as mentioned in the other thread https://github.com/ohmybash/oh-my-bash/issues/115#issuecomment-1961179006 and have time to create a PR and address requests for changes, PR is welcome.

> I will often decline to perform oh-my-bash updates so that I don't have to go back and re-edit my .bashrc.

The update procedure of Oh My Bash doesn't change `~/.bashrc`. Oh My Bash touches `~/.bashrc` only when it is installed.

**Comment by Steve973** [comment]
It only changes it the first time?  I remember running an update and having to restore a backup to get my non-OMB updates restored.  I cannot remember everything *exactly* but I'm about 95% sure.  I'll try it again and see what happens.  If I'm wrong I'd be glad to admit it in case anybody else looks through tickets and finds this one.  If you don't hear from me, it means that I haven not gotten to it, yet.  Please don't hesitate to ping me if I haven't gotten back to you in a decent amount of time.  I see that it has already been over 2 months, and that seems like it has already been too long.  I will try to get to it by this weekend.

**Comment by Steve973** [comment]
Actually, it's probably not fair to you (or to the project) to keep this open for so long.  I will close this for now, especially since you said that it only edits the bashrc file on the original install, and not on the updates.  I'll assume that this is my mistake, and I'll open another ticket when I get a chance to really look into this, if an update messes something up.  Thank you for being patient since Feb 23!
