### ISSUE TITLE
Robby russell theme issue

### ISSUE THREAD

**Issue by narasimha00** [ohmybash/oh-my-bash#534]
Robby russell theme isn't showing the python venv/condavenv information even after enabling it in `.bashrc` file

**Comment by akinomyoga** [comment]
Right, `robbyrussell` theme doesn't support the python environment information. The features supported by each theme are not necessarily the same as others. Some themes support feature X, while others support feature Y, etc. If you would like to include the python environment information in theme `robbyrussell`, a PR is welcome.

**Comment by narasimha00** [comment]
Okay thanks ! I will try my best :D
