### ISSUE TITLE
sudo: _omb_util_alias_init_mv: command not found

### ISSUE THREAD

**Issue by stueja** [ohmybash/oh-my-bash#544]
Trying to `mv` files like

```bash
sudo mv *ttf /usr/share/fonts/TTF
```
results in the above error even after upgrade:

```bash
09:21:43 jan@two-arch ttf-gowun-batang ±|master ✗|→ upgrade_oh_my_bash 
Updating Oh My Bash
remote: Enumerating objects: 96, done.
remote: Counting objects: 100% (96/96), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 76 (delta 49), reused 53 (delta 27), pack-reused 0
Unpacking objects: 100% (76/76), 38.04 KiB | 1.81 MiB/s, done.
From https://github.com/ohmybash/oh-my-bash
 * branch            master     -> FETCH_HEAD
   632fd71..4c2afd0  master     -> origin/master
Updating 632fd71..4c2afd0
Fast-forward
 completions/docker-compose.completion.sh  |  600 +----
 completions/docker.completion.sh          | 3013 +------------------------
 completions/fallback/docker-compose.bash  |  685 ++++++
 completions/fallback/docker.bash          | 5611 ++++++++++++++++++++++++++++++++++++++++++++++
 lib/omb-prompt-base.sh                    |   11 +-
 plugins/bashmarks/README.md               |   23 +-
 themes/THEMES.md                          |    4 +
 themes/bakke/bakke.theme.sh               |   10 +-
 themes/powerline/powerline.base.sh        |    6 +-
 themes/purity/purity.theme.sh             |    4 +-
 themes/robbyrussell/robbyrussell.theme.sh |   21 +-
 themes/roderik/roderik.theme.sh           |   21 +-
 12 files changed, 6451 insertions(+), 3558 deletions(-)
 create mode 100644 completions/fallback/docker-compose.bash
 create mode 100644 completions/fallback/docker.bash
         __                          __               __  
  ____  / /_     ____ ___  __  __   / /_  ____ ______/ /_ 
 / __ \/ __ \   / __ `__ \/ / / /  / __ \/ __ `/ ___/ __ \
/ /_/ / / / /  / / / / / / /_/ /  / /_/ / /_/ (__  ) / / /
\____/_/ /_/  /_/ /_/ /_/\__, /  /_.___/\__,_/____/_/ /_/ 
                        /____/                            
Hooray! Oh My Bash has been updated and/or is at the current version.
To keep up on the latest news and updates, follow us on GitHub: https://github.com/ohmybash/oh-my-bash

09:21:53 jan@two-arch ttf-gowun-batang ±|master ✗|→ sudo mv *ttf /usr/share/fonts/TTF/
[sudo] password for jan: 
sudo: _omb_util_alias_init_mv: command not found
```

Same for `cp` 

This is on Arch Linux, 6.7.9-arch1-1, with GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu)

**Comment by akinomyoga** [comment]
The problem doesn't reproduce in my environment. I suspect `sudo` in your environment is defined to be an alias ending with a space. What is the result of the following command?

```bash
$ type -a sudo
```

**Comment by stueja** [comment]
```
11:40:00 ***@***.*** Downloads → type -a sudo
sudo is aliased to `sudo '
sudo is /usr/bin/sudo
```

Ah, yes, you are right, I forgot about that.
I did that to use the alias "vim" which is mapped to "/usr/bin/nvim" also
when prefixed with "sudo" (https://askubuntu.com/a/22043).

Am Mi., 27. März 2024 um 09:55 Uhr schrieb Koichi Murase <
***@***.***>:

**Comment by stueja** [comment]
```
11:40:00 ***@***.*** Downloads → type -a sudo
sudo is aliased to `sudo '
sudo is /usr/bin/sudo
```

Ah, yes, you are right, I forgot about that.
I did that to use the alias "vim" which is mapped to "/usr/bin/nvim" also
when prefixed with "sudo" (https://askubuntu.com/a/22043).

```
11:41:40 jan@two-arch Downloads → sudo vim --version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
11:41:43 jan@two-arch Downloads → \sudo vim --version
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Mar 05 2024 22:43:21)
```

**Comment by akinomyoga** [comment]
OMB doesn't define that alias of `sudo`, so this is technically a conflict between OMB and the custom alias `sudo`. I wouldn't change the current settings of OMB, but you can work around it.

- For example, you can disable `general` plugin (by removing the entry `general` from the array `plugins` in `~/.bashrc`) because those aliases of `mv` and `cp` are defined by the `general` plugin.
- Or another way is to undefine the aliases `mv` and `cp` after sourcing `"$OSH"/oh-my-bash.sh` in `~/.bashrc`. You can undefine them by putting `unalias mv cp` in your `~/.bashrc`.

**Comment by stueja** [comment]
I went for unaliasing cp and mv, works like a charm.
Thank you very much for your quick replies and fix!

**Comment by akinomyoga** [comment]
Great!

**Comment by dariusarnold** [comment]
@akinomyoga What functionality, if any, do I lose when disabling the `general` plugin?

**Comment by akinomyoga** [comment]
There is no documentation now, but you can look at the file [`aliases/general.aliases.sh`](https://github.com/ohmybash/oh-my-bash/blob/0b218263fd456a6f3e7a84777385653f7070148a/aliases/general.aliases.sh) to check what aliases are defined.

**Comment by akinomyoga** [comment]
@dariusarnold I added descriptions in a new file [`general.aliases.md`](https://github.com/ohmybash/oh-my-bash/blob/b1387f27e811734a14170f0d8e7c8058d5913f6d/aliases/general.aliases.md).

**Comment by ICHx** [comment]
I got the same issue.  it'd be better to not override cp and mv by default rather with a switch

**Comment by ICHx** [comment]
Thanks, I did remove "general" in bashrc.  Thanks for mentioning unalias, I didn't know that exists
