### ISSUE TITLE
Theme not being applied

### ISSUE THREAD

**Issue by simon-pearson** [ohmybash/oh-my-bash#551]
Hello, I am trying to use oh-my-bash to apply a theme to my terminal. Here's the info about my stack:

* O/S: RHEL 9.3 (Plow) running on a 64-bit system.
* Terminal: Version 3.40.3 for GNOME 40

I have selected the "agnoster" theme in my `.bashrc` file:

```bash
 ✘ simon@localhost  ~  cat ~/.bashrc | grep -i OSH_THEME
OSH_THEME="agnoster"
```

Here's a screenshot of what my terminal looks like, although I have the "agnoster" theme selected:

![image](https://github.com/ohmybash/oh-my-bash/assets/24149735/953bae60-4f88-4c0d-8f95-43e8586a7254)

It feels like something else is interfering and preventing the theme being applied, can anyone help point me in the right direction?

**Comment by simon-pearson** [comment]
Apologies, I see this would be better placed in 'Discussions' - closing issue.

**Comment by akinomyoga** [comment]
Actually, either works.
