### ISSUE TITLE
Theme: wanelo throws error

### ISSUE THREAD

**Issue by wertzuz** [ohmybash/oh-my-bash#564]
When theme is loaded an Error is thrown after each command.
Error: ```-bash: return: ❤️: numeric argument required```
 Bash Version: ```GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu)```

![image](https://github.com/ohmybash/oh-my-bash/assets/97708601/6061631d-4fda-49cd-a8cd-5ecd87f61735)

**Comment by akinomyoga** [comment]
Thanks for the report.
