### ISSUE TITLE
How to change time from 12H to 24H.

### ISSUE THREAD

**Issue by retxrika** [ohmybash/oh-my-bash#571]
Hello!

In the "ohmyzsh" project there was exactly the same question, but there it was solved very simply: Please tell me how to do the same for this project. The theme in my case is "Font".

![image](https://github.com/ohmybash/oh-my-bash/assets/47078259/845e52c1-507f-4fff-a733-fd462e11ec2e)

**Comment by retxrika** [comment]
Link to previous question in "ohmyzsh":
https://github.com/ohmyzsh/ohmyzsh/issues/9387

**Comment by jvitorinoj** [comment]
`export THEME_CLOCK_FORMAT="%H:%M:%S"`

Set the var THEME_CLOCK_FORMAT  in $HOME/.oh-my-bash/themes/font/font.theme.sh to a permanent change
