### ISSUE TITLE
More package-friendly

### ISSUE THREAD

**Issue by blackteahamburger** [ohmybash/oh-my-bash#589]
It will be better if there's a way to tell oh-my-bash the way to update the package for `upgrade_oh_my_bash` like `_package.bash` in [ble.sh](https://github.com/akinomyoga/ble.sh) when oh-my-bash is installed by a package manager. Thanks!

**Comment by akinomyoga** [comment]
I'm not sure if Oh My Bash is designed so that it can be a system package, but I think the equivalent to `_package.bash` is `tools/upgrade.sh`. You can overwrite it.

**Comment by blackteahamburger** [comment]
It is not very graceful but it works. Close this.
