### ISSUE TITLE
Problem with agnoster theme.

### ISSUE THREAD

**Issue by PushkarBharambe** [ohmybash/oh-my-bash#59]
Making agnoster as default theme, the terminal displays a message saying "No such file of directory" for the file agnoster.theme.sh. When I looked into the directory, their is a file named agnoster-bash.theme.sh

**Comment by PushkarBharambe** [comment]
Of course not! I was looking in .oh-my-bash/themes itself.
And their was no file named agnoster.theme.sh

**Comment by rpotter12** [comment]
@PushkarBharambe As you said their was no file named agnoster.theme.sh
Copy agnoster theme folder from oh-my-bash/themes to .oh-my-bash/themes

**Comment by PushkarBharambe** [comment]
Their is also no file named agnoster.theme.sh in the folder oh-my-bash/themes and even on the github repo. Please check it.

**Comment by Kreyren** [comment]
Fixed in https://github.com/ohmybash/oh-my-bash/pull/71
