### ISSUE TITLE
Bug with Vim auto-completion

### ISSUE THREAD

**Issue by Yangyang96** [ohmybash/oh-my-bash#598]
I encountered `bash: eval: line -849: syntax error near unexpected token `('
bash: eval: line -849: `compgen -f -X !!(*.@(o|so|so.!(conf)|a|[rs]pm|gif|jp?(e)g|mp3|mp?(e)g|avi|asf|ogg|class)|*.@(O|SO|SO.!(CONF)|A|[RS]PM|GIF|JP?(E)G|MP3|MP?(E)G|AVI|ASF|OGG|CLASS)) -- $(quote_readline $cur)'` in terminal display for `vim` auto-completion with the latest version.

**Comment by akinomyoga** [comment]
This seems like a very old bug of bash-completion 2.1 fixed by https://github.com/scop/bash-completion/commit/b65232fa34e310cf357e2ff4b8921e50e260d294. Oh My Bash (OMB) doesn't provide the completion setting for Vim, but it loads `bash-completion` when it finds a copy of `bash-completion` in the system. I suspect the `bash-completion` loaded in the session is an old version with a bug.

What are the results of the following commands?

```bash
$ declare -p BASH_VERSINFO BASH_COMPLETION_VERSINFO
$ (shopt -s extdebug; declare -F _filedir_xspec)
$ grep RELEASE /usr/share/bash-completion/bash_completion
```

**Comment by Yangyang96** [comment]
> This seems like a very old bug of bash-completion 2.1 fixed by [scop/bash-completion@b65232f](https://github.com/scop/bash-completion/commit/b65232fa34e310cf357e2ff4b8921e50e260d294). Oh My Bash (OMB) doesn't provide the completion setting for Vim, but it loads `bash-completion` when it finds a copy of `bash-completion` in the system. I suspect the `bash-completion` loaded in the session is an old version with a bug.
> 
> What are the results of the following commands?
> 
> ```shell
> $ declare -p BASH_VERSINFO BASH_COMPLETION_VERSINFO
> $ (shopt -s extdebug; declare -F _filedir_xspec)
> $ grep RELEASE /usr/share/bash-completion/bash_completion
> ```
> 
> **edit**: In addition, what is the result of the following command?
> 
> ```shell
> $ shoot | grep extglob
> ```

```shell
$ declare -p BASH_VERSINFO BASH_COMPLETION_VERSINFO
```
> declare -ar BASH_VERSINFO='([0]="3" [1]="2" [2]="57" [3]="1" [4]="release" [5]="arm64-apple-darwin23")'
-bash: declare: BASH_COMPLETION_VERSINFO: not found

```shell
$ (shopt -s extdebug; declare -F _filedir_xspec)
```
> _filedir_xspec 1581 /opt/homebrew/Cellar/bash-completion/1.3_3/etc/bash_completion

```shell
$ grep RELEASE /usr/share/bash-completion/bash_completion
```
> grep: /usr/share/bash-completion/bash_completion: No such file or directory

```shell
$ shopt | grep extglob
```
> extglob        	off

**Comment by akinomyoga** [comment]
Thank you for the information. OK, so it means that you use bash-3.2.57 and bash-completion-1.3. In addition, `extglob` is turned off. `extglob on` is required by `bash-completion`. OMB turns on `extglob`, but somehow the `extglob` is turned off in your environment.

Do you turn off `extglob` (by {`shopt -u extglob`) somewhere in your `~/.bashrc`?

If so, you need to remove that line. You cannot turn off `extglob` as far as you have `bash-completion`.

**Comment by Yangyang96** [comment]
> Thank you for the information. OK, so it means that you use bash-3.2.57 and bash-completion-1.3 from brew. In addition, `extglob` is turned off. `extglob on` is required by `bash-completion`. OMB turns on `extglob`, but somehow the `extglob` is turned off in your environment.
> 
> Do you turn off `extglob` (by {`shopt -u extglob`) somewhere in your `~/.bashrc`?
> 
> If so, you need to remove that line. You cannot turn off `extglob` as far as you have `bash-completion`.

No, as far as I can tell, there is nowhere I turn `extglob` off, but somehow it's turned off. It does solve my problem as long as `extglob` is on, thank you!

**Comment by akinomyoga** [comment]
So you solved it by setting `shopt -s extglob`? Great! Can we close the issue?

**Comment by akinomyoga** [comment]
@Yangyang96 Can we close the issue? Or do you want to identify where `extglob` is turned on? If so, you might temporarily define the following function at the beginning of `~/.bashrc`:

```bash
shopt() {
  local IFS=$' \t\n'
  if [[ " $* " == *" extglob "* ]]; then
    echo "${BASH_SOURCE[1]}:${BASH_LINENO[0]}(${FUNCNAME[1]}): shopt $*" >/dev/tty
  fi
  command shopt "$@"
}
```

and start a new Bash session to see where `extglob` is turned on or off. If you provide the result, I can check it.

**Comment by Yangyang96** [comment]
> @Yangyang96 Can we close the issue? Or do you want to identify where `extglob` is turned on? If so, you might temporarily define the following function at the beginning of `~/.bashrc`:
> 
> ```shell
> shopt() {
>   local IFS=$' \t\n'
>   if [[ " $* " == *" extglob "* ]]; then
>     echo "${BASH_SOURCE[1]}:${BASH_LINENO[0]}(${FUNCNAME[1]}): shopt $*" >/dev/tty
>   fi
>   command shopt "$@"
> }
> ```
> 
> and start a new Bash session to see where `extglob` is turned on or off. If you provide the result, I can check it.

Sure! Thanks a lot!

**Comment by matt-horwood-mayden** [comment]
I too have a mac and this vi issue just started, I have `/opt/homebrew/Cellar/bash-completion/1.3_3/etc/bash_completion`.

using your above code I get the below
```
/Users/matt.horwood/.oh-my-bash/lib/utils.sh:307(_omb_util_get_shopt): shopt -q extglob
/Users/matt.horwood/.oh-my-bash/lib/utils.sh:409(_omb_util_glob_expand): shopt -s extglob
/Users/matt.horwood/.oh-my-bash/lib/utils.sh:9(_omb_util_get_shopt): shopt -q extglob
/Users/matt.horwood/.oh-my-bash/lib/cli.bash:49(source): shopt -s extglob
/Users/matt.horwood/.oh-my-bash/lib/cli.bash:204(source): shopt -u extglob
/Users/matt.horwood/.oh-my-bash/lib/utils.sh:307(_omb_util_get_shopt): shopt -q extglob
/Users/matt.horwood/.oh-my-bash/lib/utils.sh:409(_omb_util_glob_expand): shopt -s extglob
/Users/matt.horwood/.oh-my-bash/lib/utils.sh:423(_omb_util_glob_expand): shopt -u extglob
```

**Comment by akinomyoga** [comment]
OK, I've identified the problem. I'll later fix it.

**Comment by matt-horwood-mayden** [comment]
thanks ❤️

**Comment by akinomyoga** [comment]
Sorry for the delay. I pushed fixes in commit 1a7ef75664de1241009f10d5f0fe3d08e699526d.

**Comment by akinomyoga** [comment]
Sorry, the problem doesn't seem to be solved by commit 1a7ef75. I'll push another fix later.

**Comment by akinomyoga** [comment]
I pushed a fix 08e297c631074501a1945c224007eb043ef61bef.

**Comment by akinomyoga** [comment]
I got confirmation in #607 that the same issue has been fixed in the latest push. Let me close this issue. If you still experience the same issue in the current master branch, please reopen the issue. Thank you for your reports!

**Comment by matt-horwood-mayden** [comment]
can confirm an update and restart fixes this

**Comment by akinomyoga** [comment]
@matt-horwood-mayden Thanks for your confirmation!
