### ISSUE TITLE
Incorrect symbols on powerbash10k theme

### ISSUE THREAD

**Issue by phantazeeer** [ohmybash/oh-my-bash#639]
I installed oh-my-bash and changed theme in .bashrc file, when I restarted it, and saw this 
![image](https://github.com/user-attachments/assets/0e702706-0a2f-466f-ae2f-c9099fee7537)
I tried downloading powerline-fonts and change font, but I don't know which font should i choose.
I'm using Fedora 40 and Gnome Terminal

**Comment by akinomyoga** [comment]
As far as I search the code points, these characters seem to be included in Nerd Fonts but not in Powerline fonts.

**Comment by phantazeeer** [comment]
**I managed to install Nerd Fonts and it fixed incorrect symbols, *thanks for help*.**
It also would be cool, if people, who is not good at Linux customization, could know that they should install some other font from README in theme.
