### ISSUE TITLE
Tab-Auto Complete show ~/.oh-my-bash files

### ISSUE THREAD

**Issue by sarthakmisraa** [ohmybash/oh-my-bash#64]
when in any directory, command
```
07:06:47 duckie@blackperl nice → ls
python
07:06:50 duckie@blackperl nice → cd p
plugin   plugins  purple   python/ 

```
then tab to autocomplete shows files that are present in ~/.oh-my-bash along with current directory.
This becomes a problem when your working directory has only one file starting with p but oh-my-bash shows 3 options that are not even there

**Comment by nntoan** [comment]
Hi @sarthakmisraa , can you please tell us a little bit regards which OS and Bash version you are using?

**Comment by sarthakmisraa** [comment]
here are the required details
1.) uname -a
```
Linux blackperl 4.18.0-24-generic #25~18.04.1-Ubuntu SMP Thu Jun 20 11:13:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux 
```
2.) Distro name and release
```DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```
3.) Bash version
```GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)```

**Comment by Kreyren** [comment]
Outdated issue assuming that i dont have this problem -> outdated -> P5

@sarthakmisraa please verify if the issue is still present for it to be investigated.

**Comment by sarthakmisraa** [comment]
yes it fixed now, thank you
