### ISSUE TITLE
-bash: printf: `)': invalid format character when using progress plugin

### ISSUE THREAD

**Issue by pjeansonzilliant** [ohmybash/oh-my-bash#646]
I have added progress to my plugins in .bashrc.
`plugins=(
  git
  bashmarks
  progress
)`

sourced .bashrc, even restarted the terminal but getting the below:

>  pierre  ~   progress 30 "hello"
-bash: printf: `)': invalid format character
[..........................] (0-bash: printf: `)': invalid format character
[#.........................] (5-bash: printf: `)': invalid format character
[##........................] (10-bash: printf: `)': invalid format character
[###.......................] (15-bash: printf: `)': invalid format character
[####......................] (20-bash: printf: `)': invalid format character
[#####.....................] (25-bash: printf: `)': invalid format character
[######....................] (30 

I'm using WSL with Ubutu 22.04

**Comment by akinomyoga** [comment]
Thanks for the report. I have fixed it in the latest push 1d43ab72a6321b0b12e805fc177ac79c8b65b2b5.
