### ISSUE TITLE
Issue with working directory and title on Mac OS

### ISSUE THREAD

**Issue by mgtest42** [ohmybash/oh-my-bash#67]
Bash version: 5.0.7(1)-release
OMB version: f23792a782db3b8a945d24cdd0266c169a4d5dd5
MacOS Mojave 10.14.5 (18F132)

After enabling oh-my-bash, bash ignores terminal settings - "open the same working directory in the new tab" and always opens the home directory, also the title of the terminal is "-bash" instead of the current directory (like it was previously).

I'm not too familiar with bash and not sure is it a bug of oh-my-bash or expected behavior. Could you guide me on how to fix this?

**Comment by mgtest42** [comment]
If I redefine PROMPT_COMMAND everything is wrorking:
```
PROMPT_COMMAND='rm "${HOME}/.cwd" && echo $(pwd) > "${HOME}/.cwd"'
[[ -f "${HOME}/.cwd" ]] && cd "$(cat ${HOME}/.cwd)"
```

But do this trying to preserve OMB PROMPT_COMMAND doesn't:
```
safe_append_prompt_command "rm ${HOME}/.cwd && echo $(pwd) > ${HOME}/.cwd"
[[ -f "${HOME}/.cwd" ]] && cd "$(cat ${HOME}/.cwd)"
```

**Comment by mgtest42** [comment]
My solution is:
```
PROMPT_COMMAND='echo -ne "\033]0;${PWD##*/}\007";echo $(pwd) >| ${HOME}/.cwd;prompt_command'
[[ -f "${HOME}/.cwd" ]] && cd "$(cat ${HOME}/.cwd)"
function cleanup_cwd {
  rm ${HOME}/.cwd
}
trap cleanup_cwd EXIT
```

But I'm not sure, that it's the best option, so still, I look for the help of someone more experienced.

**Comment by mgtest42** [comment]
The final solution is:
```
# Open new tabs in the same directory
function chpwd {
if [[ $TERM_PROGRAM == "Apple_Terminal" ]]; then
    local SEARCH=' '
    local REPLACE='%20'
    local PWD_URL="file://$HOSTNAME${PWD//$SEARCH/$REPLACE}"
    printf '\e]7;%s\a' "$PWD_URL"
fi
}
safe_append_prompt_command "chpwd"

# show current folder in title
safe_append_prompt_command 'echo -ne "\033]0;${PWD##*/}\007
```

**Comment by codeseedr** [comment]
@mgtest42 Thanks a lot for your fix! I appended it to my `~/.bashrc` file having terminated the last line with `"'` (double-quote, single-quote). It works pretty well in general (most importantly CWD gets preserved when opening a new tab), although the tab title gets formatted as `$cwd --- -bash`, while I would prefer it be just plain simple `$cwd` (I'm on macOS 10.13.6). Great stuff anyway, thanks again!
