### ISSUE TITLE
"_command_exists" used in battery plugin but is not defined anywhere!

### ISSUE THREAD

**Issue by antofthy** [ohmybash/oh-my-bash#68]
TLDR: `command_exists()` is defined in https://github.com/ohmybash/oh-my-bash/blob/429ffc1cbcd1a14f7ec0241a2e898d339eb634b6/lib/base.sh#L267, but it's not used in https://github.com/ohmybash/oh-my-bash/blob/master/plugins/battery/battery.plugin.sh which expects `_command_exists()` where `_` prefix is important.

Summarized by @Kreyren 

---

Title basically says it all...

A function "`_command_exists`" is used in the battery plugin, but is not defined anywhere else in the repository. 

*... removed personal "`cmd_found`" equivalent function, designed for older shells ...*

**Comment by antofthy** [comment]
ASIDE:  I also recommend breaking the percentage bar graph out to a separate utility.
As generating a bar graph from a percentage is a very useful thing to have.
Example (not as good)....
    http://www.ict.griffith.edu.au/anthony/software/#percent
script
    http://www.ict.griffith.edu.au/anthony/software/percent.sh.txt

**Comment by Kreyren** [comment]
Assigned P2 as bug.

Investigation needed -> Currently fix unknown.

**Comment by Kreyren** [comment]
@antofthy `_command_exists` where? (repository is using 3rd party code for completetion etc..)

**Comment by Kreyren** [comment]
Lowering priority untill info is provided

**Comment by antofthy** [comment]
More information... Okay...

The plug-in "`plugins/battery/battery.plugin.sh`" used a function  `_command_exists` multiple times (over a dozen). And yet a search of the whole repository did not turn up that function anywhere else, except in that plugin.  It is simply not defined anywhere.

On the other hand in "`lib/base.sh`" a function "`command_exists()`" is defined!
```bash
command_exists () {
  type "$1" &> /dev/null ;
}
```
And in "`lib/utils.sh`" a simular function "`type_exists()`" is also defined...
```bash
type_exists() {
  if [ "$(type -P "$1")" ]; then
    return 0
  fi
  return 1
}
```
Which could be rewritten more concisely as...
```bash
type_exists() {
  [ "$(type -P "$1")" ]
}
```
Though checks if the given argument is an external command, and ignores functions of the same name.   But its is used for same purpose.

In summery.   The plug-in is broken. And in looking for a fix I found the two different functions being used for the same purpose.  One probably should replace the other.

**Comment by Kreyren** [comment]
type_exists was referenced in #103 

contributions are welcomed since i'm trying to improve the code quality pasively (since it needs rewriting of lots of things)

---

About the `command_exists()` and `_command_exists()` it's stupid, but it doesn't create conflicts since they are different. 

ping @nntoan How do you want to resolve conflicts alike?

**Comment by Kreyren** [comment]
@antofthy Referencing #104 if only command_exists is the issue this should fix it.
