### ISSUE TITLE
REQUEST: Write access

### ISSUE THREAD

**Issue by Kreyren** [ohmybash/oh-my-bash#88]
Requesting write access to oh-my-bash.

**Comment by Kreyren** [comment]
Blocked by : https://github.com/ohmybash/oh-my-bash/issues/89

**Comment by nntoan** [comment]
@Kreyren I've sent you an invitation to the Maintainer team of Oh My Bash! Welcome on board :) 🎉

**Comment by Kreyren** [comment]
Closing as resolved.
