### ISSUE TITLE
NOTICE: Improved priority handling

### ISSUE THREAD

**Issue by Kreyren** [ohmybash/oh-my-bash#96]
Attempting to improve priority handling to manage our time maintaining better. 

Feedback wanted.

@nntoan Decided to perform this on my name since you take time to answer which blocks Merges/issues -> was hoping to improve this by making this priority management will undo if you don't like it.

**Comment by Kreyren** [comment]
Assigned P1 since this is beeing currently investigated and affects whole repository.

**Comment by Kreyren** [comment]
Added `MAC-OS` and `LINUX` labels, requesting sanity check for these -> expecting to blacklist `MAC-OS` on my end since i'm not using this OS.

**Comment by nntoan** [comment]
@Kreyren This is good, I liked the colours. Let do this 💯

**Comment by Kreyren** [comment]
Closing as solved
